### ISSUE TITLE
仪表盘最近告警列表显示错误

### ISSUE THREAD

**Issue by gcdd1993** [dromara/hertzbeat#100]
**Describe the bug**
仪表盘最近告警列表未显示数据

**Used Version**  
1.0 beta7

**To Reproduce**
1、使用浏览器，后退（退至非仪表盘页面）
2、然后前进到仪表盘，最近告警列表未展示。
3、查看接口，发现返回了数据，但是前端页面未展示
4、前端定时器会刷新此问题，所以只在第一次退至仪表盘会显示错误。

**Expected behavior**
应该展示4条报警记录

**Screenshots**
![image](https://user-images.githubusercontent.com/26523525/163713240-13af8df2-dbbf-41b8-abc0-d906e7618d83.png)

**Additional context**
前端BUG

**Comment by tomsun28** [comment]
thanks,  we will fix it next version.
