### ISSUE TITLE
[Task] hertzbeat metrics collector cluster design

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1003]
### why collector cluster? 

- cluster means more powerful performance and can support monitoring more
- unified monitoring between different isolated networks, one hertzbeat can monitoring multi isolated networks resource.
- avoid single point of failure 

### desgin discuss

![image](https://github.com/dromara/hertzbeat/assets/24788200/d7e6650e-5e22-484a-bc88-9fee47cbea81)

**Comment by Ceilzcx** [comment]
讨论存疑：
1. 采集后数据的存储位置？
    主hz（collector每次采集完需要将数据同步到主hz，需要处理各种丢包等问题，带宽使用高）
    collector模块自己存储（无法实现内网的collector，通过外网查询）
2. hz如何配置collector模块的地址？
    配置文件
    数据库
3. 心跳机制，collector向hz发送心跳还是hz向collector发送心跳？
4. hz如何响应collector模块的上线，注销，连接失败，重连接等问题？

**Comment by zqr10159** [comment]
在监控量不大的情况下，是否保留原来的模式，以简化部署难度？当初就是看着hz不用额外部署agent才用的

**Comment by tomsun28** [comment]
> 在监控量不大的情况下，是否保留原来的模式，以简化部署难度？当初就是看着hz不用额外部署agent才用的

是的，默认还是会单体 all in one. 设计时也会尽量减少外部组件依赖

**Comment by l646505418** [comment]
> > 在监控量不大的情况下，是否保留原来的模式，以简化部署难度？当初就是看着hz不用额外部署agent才用的
> 
> 是的，默认还是会单体 all in one. 设计时也会尽量减少外部组件依赖

如果在主 hz中提供webhook來接收其他collector的信息会不会减少对kafka的依赖

**Comment by tomsun28** [comment]
> > > 在监控量不大的情况下，是否保留原来的模式，以简化部署难度？当初就是看着hz不用额外部署agent才用的
> > 
> > 
> > 是的，默认还是会单体 all in one. 设计时也会尽量减少外部组件依赖
> 
> 如果在主 hz中提供webhook來接收其他collector的信息会不会减少对kafka的依赖

可以有 把它做成可配置的形式 默认webhook

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > In the case of a small amount of monitoring, is the original mode retained to simplify the difficulty of deployment? At the beginning, it was only used when looking at hz without additional deployment of agent
> >
> >
> > Yes, the default is still all in one. The design will also minimize external component dependencies
>
> If webhook is provided in the main hz to receive information from other collectors, will it reduce the dependence on kafka

It can be made into a configurable form, the default webhook

**Comment by l646505418** [comment]
感觉这个更像是提供一个控制中心呢😂

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It feels more like providing a control center😂
