### ISSUE TITLE
2 points of advice

### ISSUE THREAD

**Issue by baixing99** [dromara/hertzbeat#1009]
### Description

希望SSL证书监控这里 在展示的时候增加一个分组

已经能一键复制已有的证书监控配置为新的证书
![QQ截图20230602102359](https://github.com/dromara/hertzbeat/assets/73473087/67287e9c-f4d6-4b7b-9eb8-5e6a87455a02)

### Task List

1 SSL监控增加分组

2 SSL证书能复制配置

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

I hope that the SSL certificate will monitor here and add a group when displaying

Already able to copy the existing certificate monitoring configuration as a new certificate with one click
![QQ screenshot 20230602102359](https://github.com/dromara/hertzbeat/assets/73473087/67287e9c-f4d6-4b7b-9eb8-5e6a87455a02)


### Task List

1 Add grouping for SSL monitoring

2 SSL certificate can copy configuration

**Comment by tomsun28** [comment]
got it. 

- [ ] support grouping for monitoring 
- [ ] support monitoring params can copy configuration by one step

**Comment by l646505418** [comment]
I can work on it, can assign to me

**Comment by l646505418** [comment]
hi，@baixing99 你能更详细地解释下分组这个功能吗？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, @baixing99 can you explain the grouping function in more detail?

**Comment by baixing99** [comment]
例如a分组里面有&nbsp;a1_SSL ;a_2SSLb分组里面有b1_SSL;b2_ssl




只是想把这些展示在页面上 相当于文件夹那样归类
因为我们的平台都是按照域名去划分的
某些域名属于某一个平台


比如 www.a.com&nbsp; admin.a.com 这样的属于一组平台&nbsp;
www.b.com&nbsp; admin.b.com 这样的属于另一组平台&nbsp;


所以我希望在页面上我可以定义一个文件夹
a.com&nbsp; 里面放属于a.com 的子域名
b同理
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月4日(星期天) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hertzbeat] 2 points of advice (Issue #1009)





 
***@***.*** 你能更详细地解释下分组这个功能吗？
