### ISSUE TITLE
[Task] <Host support IPv6 address>

### ISSUE THREAD

**Issue by guojing1983** [dromara/hertzbeat#1018]
### Description

HOST can only fill in IPv4 and domain names, and does not support filling in Ipv6 address. We hope to support this in the future.

### Task List

<future> Host support IPv6 address

**Comment by l646505418** [comment]
seems we have validate the IPV6 
![ipv6](https://github.com/dromara/hertzbeat/assets/50475131/adba1cf6-4db3-4287-a139-6c3f6802c582)

**Comment by guojing1983** [comment]
太棒了，非常感谢！

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Awesome, thank you very much!

**Comment by tomsun28** [comment]
but IPV6 seem not support actually
