### ISSUE TITLE
监控历史图表详情-点右边 按”查询 近1小时/1天/6小时按钮，一直等待转圈

### ISSUE THREAD

**Issue by zhouxingfako** [dromara/hertzbeat#102]
**Describe the bug**
告警中心-------监控历史图表详情------点右边 按”查询 近1小时/1天/6小时 等按钮“----- 一直等待转圈

**Used Version**  
v1.0.beta.7

**Comment by tomsun28** [comment]
hi, the version [hertzbeat v1.0](https://github.com/dromara/hertzbeat/releases/tag/v1.0) has fix it
