### ISSUE TITLE
[Task] <support config hertzbeat system lanuage on web ui>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1022]
### Description

support config hertzbeat system lanuage on web ui

ui design refer https://github.com/dromara/hertzbeat/issues/934 https://github.com/dromara/hertzbeat/pull/953 

<img width="1933" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/aa783621-0c9f-4a84-8240-d495389c9f05">

### Task List

- [ ] support config hertzbeat system lanuage on web ui
- [ ] help doc

**Comment by yangshuDBA** [comment]
this task is now supported。





![Image](https://github.com/dromara/hertzbeat/assets/112070510/c931965a-b12d-4ab8-a6a3-b4dc7100f7c1)
