### ISSUE TITLE
[Question] How to get in touch regarding a security concern? 

### ISSUE THREAD

**Issue by cokeBeer** [dromara/hertzbeat#1023]
### Question

Hello 👋

I found a potential security issue in hertzbeat, how can I get in touch with you in a private way and submit my security report?

Could you add a SECURITY.md file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

**Comment by tomsun28** [comment]
hi @cokeBeer welcome😊.  you can submit report to tomsun28@outlook.com , we will add SRCURITY.md later. Thanks👍👍👍

**Comment by tomsun28** [comment]
hi please try again.
________________________________
发件人: cokeBeer ***@***.***>
发送时间: 2023年6月9日 17:07
收件人: dromara/hertzbeat ***@***.***>
抄送: tomsun28 ***@***.***>; State change ***@***.***>
主题: Re: [dromara/hertzbeat] [Question] How to get in touch regarding a security concern? (Issue #1023)


Hi, maybe you should enable this ?
[image]<https://user-images.githubusercontent.com/70683161/244647264-cb27ebb9-c44c-4ef0-a3ad-0676812a7ec6.png>
[image]<https://user-images.githubusercontent.com/70683161/244647601-6a21a45d-50c3-42e4-983b-6544dc169c24.png>

―
