### ISSUE TITLE
[BUG] <The label matching of the alarm silence policy does not take effect>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The label matching of the alarm silence policy does not take effect

### Expected Behavior

Label matching takes effect

### Steps To Reproduce

<img width="1371" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/d4297c24-1a5b-4794-9319-04729da2ecb3">

### Environment

```markdown
HertzBeat version(s): v1.3.1
```

**Comment by l646505418** [comment]
do you mean can search the alarm sk=lience policy by tag? @tomsun28

**Comment by tomsun28** [comment]
no, the bug is `Tag Match` is not take effect.
eg: we config `Tag Match` tag xxx-ttt, but the `alert silence` not effect the alert with tag xxx-ttt 

<img width="299" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/4fb0fe60-d12e-4aef-a7b3-eed6cfdfc0d2">
