### ISSUE TITLE
[Question] <Error 403 reported when using admin user>

### ISSUE THREAD

**Issue by panrenjun** [dromara/hertzbeat#1032]
### Question

Linux宿主机版本：NAME="Rocky Linux" VERSION="8.7 (Green Obsidian)"
docker版本：Docker version 20.10.22, build 3a2c30b
docker compose版本：Docker Compose version v2.17.2

问题描述：在github拉取的1.3.1包，在没有修改过任何一个配置的情况下，直接进入hertzbeat-1.3.1/script/docker-compose/hertzbeat-mysql-iotdb下执行docker-compose up -d ，一切正常运行，使用admin用户登录界面添加监控没有任何问题，但是不弄进行修改删除停止操作。报错403.没有权限。期间给conf目录和dbdata目录777 权限也没有作用。
![微信截图_20230619162437](https://github.com/dromara/hertzbeat/assets/103396385/9f02553d-3e09-43e3-9627-360951b53545)
![微信截图_20230619162723](https://github.com/dromara/hertzbeat/assets/103396385/dd68a7a1-c6f9-4f5e-83a0-abb4c7d02fc9)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

Linux host version: NAME="Rocky Linux" VERSION="8.7 (Green Obsidian)"
Docker version: Docker version 20.10.22, build 3a2c30b
docker compose version: Docker compose version v2.17.2

Description of the problem: The 1.3.1 package pulled from github, without modifying any configuration, directly enters hertzbeat-1.3.1/script/docker-compose/hertzbeat-mysql-iotdb to execute docker-compose up - d, everything is running normally. There is no problem in adding monitoring using the admin user login interface, but it does not modify, delete, or stop the operation. Error 403. No permission. Giving 777 permissions to the conf directory and dbdata directory during the period has no effect.
![WeChat screenshot_20230619162437](https://github.com/dromara/hertzbeat/assets/103396385/9f02553d-3e09-43e3-9627-360951b53545)
![WeChat picture_20230619162402](https://github.com/dromara/hertzbeat/assets/103396385/69a3ac13-368a-4ca0-86e7-f20e871388c3)

**Comment by tomsun28** [comment]
got it👍

**Comment by tomsun28** [comment]
hi 我们并没有复现出来，能发一下你安装目录 docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml 的文件内容吗

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi We didn't reproduce it, can you post the file content of your installation directory docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml

**Comment by panrenjun** [comment]
在我本地环境或者阿里云服务器上都是直接可以运行并且是成功的，生产环境唯一不同于其他环境的只有一个nginx+keepalived，但是既然网页可以打开访问，可能跟这个关系不大。dockercompose运行的容器没有报错。以至于不知道从哪里寻找错误。我不确定我们的这个项目的生产环境甲方是否对机器做了现实，但是无非只是限制网络方面，对于这个403报错我想不明白。



***@***.***
 
From: tomsun28
Date: 2023-06-21 14:44
To: dromara/hertzbeat
CC: panrenjun; Author
Subject: Re: [dromara/hertzbeat] [Question] <Error 403 reported when using admin user> (Issue #1032)
hi 我们并没有复现出来，能发一下你安装目录 docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml 的文件内容吗

**Comment by tomsun28** [comment]
> 我不确定我们的这个项目的生产环境甲方是否对机器做了现实，但是无非只是限制网络方面，对于这个403报错我想不明白。

大概率对方修改了 `sureness.yml` 配置或使用 `guest`用户登录 

另外可以在这里使用者信息登记一下 https://github.com/dromara/hertzbeat/issues/1

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> I am not sure whether Party A has implemented the reality of the machine in the production environment of our project, but it is nothing more than restricting the network. I don't understand this 403 error.

There is a high probability that the other party has modified the `sureness.yml` configuration or logged in with the `guest` user

In addition, you can register user information here https://github.com/dromara/hertzbeat/issues/1
