### ISSUE TITLE
配置 oracle 报错 Got minus one from a read call,code: 17002.

### ISSUE THREAD

**Issue by BYNepenthe** [dromara/hertzbeat#1048]
### Question

配置 oracle 服务，配置界面一直转圈，docker 容器中报错如下：
org.dromara.hertzbeat.collector.collect.database.JdbcCommonCollect - Jdbc sql error: IO Error: Got minus one from a read call (CONNECTION_ID=37z/8u2BTQ6uzXBWGTOsCg==), code: 17002.

其他客户端连 oracle 没问题；
oracle 版本：19c，docker 部署的

![image](https://github.com/dromara/hertzbeat/assets/7778022/51007ace-1bee-44a2-a11d-e61b1d83ece3)

![image](https://github.com/dromara/hertzbeat/assets/7778022/b17afc13-3332-4e3b-a0f1-178207862c01)

![image](https://github.com/dromara/hertzbeat/assets/7778022/10ff7764-4e90-44ab-99a3-9bd04649da93)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

Configure the oracle service, the configuration interface keeps turning around, and the error is reported in the docker container as follows:
org.dromara.hertzbeat.collector.collect.database.JdbcCommonCollect - Jdbc sql error: IO Error: Got minus one from a read call (CONNECTION_ID=37z/8u2BTQ6uzXBWGTOsCg==), code: 17002.

Other clients have no problem connecting to oracle;
oracle version: 19c, deployed by docker


![image](https://github.com/dromara/hertzbeat/assets/7778022/51007ace-1bee-44a2-a11d-e61b1d83ece3)

![image](https://github.com/dromara/hertzbeat/assets/7778022/b17afc13-3332-4e3b-a0f1-178207862c01)

**Comment by BYNepenthe** [comment]
监听其他 docker 安装的 oracle 没问题，可能是有什么限制导致的

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It is no problem to listen to oracle installed by other dockers, which may be caused by some restrictions
