### ISSUE TITLE
[Question] The HertzBeat PING connectivity function deployed on the host cannot be connected

### ISSUE THREAD

**Issue by protectedMan** [dromara/hertzbeat#1049]
### Question

![image](https://github.com/dromara/hertzbeat/assets/17565737/5fa958f7-5a83-4c03-927f-2a1b5fe13e82)
试了下其他功能，SSL证书监控都是正常的，目前发现PING connectivity就是无法连通，相同的监控配置在SaaS版本的HertzBeat是正常的。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

![image](https://github.com/dromara/hertzbeat/assets/17565737/5fa958f7-5a83-4c03-927f-2a1b5fe13e82)
I tried other functions, and the SSL certificate monitoring is normal. At present, it is found that the PING connectivity cannot be connected. The same monitoring configuration is normal in the SaaS version of HertzBeat.

**Comment by tomsun28** [comment]
@protectedMan hi 请问是否是安装包部署，ping功能在安装包部署情况下需要java使用root权限启动才生效，docker环境部署无需改动

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@protectedMan hi May I ask if it is the deployment of the installation package? The ping function requires java to be started with root privileges in the case of installation package deployment to take effect. The deployment of the docker environment does not need to be changed.
