### ISSUE TITLE
[BUG] The linux system monitors the disk usage rate. There are 2 disks, which reach the threshold of the system disk and do not trigger an alarm

### ISSUE THREAD

**Issue by qq471754603** [dromara/hertzbeat#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

linux系统监控磁盘使用率,有2块磁盘,达到系统盘的阈值,不触发告警
![图片](https://github.com/dromara/hertzbeat/assets/23146592/7a5aeae7-12d5-4295-89f3-0e44745dff9e)
![图片](https://github.com/dromara/hertzbeat/assets/23146592/5488c1a4-8067-447f-9ec2-6ec4e2a8c61d)

### Expected Behavior

系统盘和外挂的数据盘,分别监控

### Steps To Reproduce

.................

### Environment

```markdown
HertzBeat version(s):v1.3.2
```

### Debug logs

................

### Anything else?

............

**Comment by tomsun28** [comment]
是告警中心没有告警信息吗 阈值是否开启应用全局，如果没有需要阈值关联监控

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there no alarm information in the alarm center? Whether the threshold is enabled and applied globally. If not, threshold correlation monitoring is required.

**Comment by qq471754603** [comment]
邮件没有,告警信息也没有
![图片](https://github.com/dromara/hertzbeat/assets/23146592/48434357-a9fb-44cf-8eab-cc4a193ba167)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
No mail, no warning information
![Image](https://github.com/dromara/hertzbeat/assets/23146592/48434357-a9fb-44cf-8eab-cc4a193ba167)

**Comment by qq471754603** [comment]
![图片](https://github.com/dromara/hertzbeat/assets/23146592/5e30a51a-3103-4bf9-bb80-2e3061dc60e2)
![图片](https://github.com/dromara/hertzbeat/assets/23146592/b7aab6d4-8e13-473f-96b5-a82aed9b50d2)
设置了65%,实际是62%,没触发

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![Image](https://github.com/dromara/hertzbeat/assets/23146592/5e30a51a-3103-4bf9-bb80-2e3061dc60e2)
![Image](https://github.com/dromara/hertzbeat/assets/23146592/b7aab6d4-8e13-473f-96b5-a82aed9b50d2)
Set 65%, the actual is 62%, not triggered

**Comment by tomsun28** [comment]
你加的监控类型是否和阈值对象类型一致，比如你阈值对象是 Linux操作系统 但你加的却是 Ubuntu操作系统

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is the monitoring type you added consistent with the threshold object type? For example, your threshold object is the Linux operating system but the one you added is the Ubuntu operating system.
