### ISSUE TITLE
email error

### ISSUE THREAD

**Issue by fudadada** [dromara/hertzbeat#1062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

smtp.partner.outlook.cn
port:587
email: xxx@xxxxxx.com
password: xxxxxxx

### Expected Behavior

报错无法发送邮件，无法使用365邮箱

### Environment

```markdown
HertzBeat version(s):
```

### Debug logs

无

### Anything else?

以及添加机器无法使用密钥认证

**Comment by tomsun28** [comment]
hi 是报什么错内容了 可以百度下那个报错 注意密钥不是账户密码是授权码。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, what is the wrong content? You can download the error on Baidu. Note that the key is not the account password but the authorization code.

**Comment by fudadada** [comment]
[电子邮件通知错误] 消息失败：com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 发送邮件需要 STARTTLS [BJXPR01CA0050.CHNPR01.prod.partner.outlook.cn 2023-07-03T07:17:07.624Z 08DB7565CE20173C]     

这个是报错信息

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[Email Notification Error] Message failed: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 Sending mail requires STARTTLS [BJXPR01CA0050.CHNPR01.prod.partner.outlook.cn 2023-07-03T07:17:07.624Z 08DB7565CE20173C ]

This is an error message

**Comment by fudadada** [comment]
我用的是365邮箱普通密码认证

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I use 365 mailbox common password authentication

**Comment by tomsun28** [comment]
> 我用的是365邮箱普通密码认证

hi 收到 我们发现这是个新出bug 感谢反馈 
会在这两天刷新版本修复

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> I am using 365 mailbox ordinary password authentication

hi received we found that this is a new bug thanks for the feedback
The version will be refreshed and fixed in these two days
