### ISSUE TITLE
[Question] Do you consider supporting spark?

### ISSUE THREAD

**Issue by melin** [dromara/hertzbeat#1074]
### Question

 是否考虑支持spark？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

 Are you considering supporting spark?

**Comment by tomsun28** [comment]
hi, the spark monitoring is in progress now. https://github.com/dromara/hertzbeat/issues/990
