### ISSUE TITLE
[BUG] <When monitoring overseas servers, fill in the host with the domain name and the connection fails>

### ISSUE THREAD

**Issue by 1130600015** [dromara/hertzbeat#1078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

docker方式启动的项目，监控海外云服务器时，填的host是域名填写，容器启动 开始是可以正常监控服务器的，但是后面他采集的信息就停在一个较早的时间，然后编辑这个监控时，测试这个监控显示的错误是
<img width="595" alt="image" src="https://github.com/dromara/hertzbeat/assets/67859663/ced1e82f-45f4-4705-be3d-cf2aaea57c93">
但是主机填ip可以测试连接就正常。在宿主机上ping该域名也是能正常解析的。部分海外ubuntu服务器出现该问题，国内暂无，我所有监控的host都填写的是域名

### Environment

```markdown
HertzBeat version(s):1.3.2
```

**Comment by tomsun28** [comment]
hi 1.4.0版本提供了关闭ssh连接复用的监控参数选项，可以解决open failed的问题

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi version 1.4.0 provides a monitoring parameter option to disable ssh connection multiplexing, which can solve the problem of open failed
