### ISSUE TITLE
docer-compose.yaml  may be  has  error

### ISSUE THREAD

**Issue by wkke** [dromara/hertzbeat#108]
volumes:
      - ./conf/application.yml:/opt/hertzbeat/config/application.yml
      - ./conf/sureness.yml:/opt/hertzbeat/config/sureness.yml

**Additional context**
执行 docker-compose时  
![image](https://user-images.githubusercontent.com/13965614/165201547-8f1d4604-6177-4301-ab85-1cddfd2ae51a.png)
看起来是挂载卷的volumes  ，参数不能是文件只能是目录吧

**Comment by tomsun28** [comment]
看日志是本地挂载的 application.yml sureness.yml 应是文件类型而不是文件夹，排查下呢，或者重新创建个 application.yml sureness.yml 文件试试
