### ISSUE TITLE
[BUG] <The startup process should not have to read all files under define>

### ISSUE THREAD

**Issue by Mr-zhou315** [dromara/hertzbeat#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我碰到一个事件如下：
我的目录权限是非root，但是在进行自定义监控时候，在define目录下面创建了一个root权限的.yml监控示例文件，导致软件无法启动，报错
![5e4d281e60db41ba40cfcac1fab3463](https://github.com/dromara/hertzbeat/assets/10276100/277959df-8bd3-4869-ae51-b80000040c6d)
我删除了这个文件之后，依然无法启动，然后发现还有个隐藏的.yml.swp文件存在，也是root权限，导致无法启动，删除之后软件恢复正常。

建议软件启动可以跳过权限不正确、配置不正确的文件，然后日志中能提示。

### Expected Behavior

应该是跳过权限不正确的文件。

### Steps To Reproduce

我碰到一个事件如下：
我的目录权限是非root，但是在进行自定义监控时候，在define目录下面创建了一个root权限的.yml监控示例文件，导致软件无法启动，报错
![5e4d281e60db41ba40cfcac1fab3463](https://github.com/dromara/hertzbeat/assets/10276100/277959df-8bd3-4869-ae51-b80000040c6d)
我删除了这个文件之后，依然无法启动，然后发现还有个隐藏的.yml.swp文件存在，也是root权限，导致无法启动，删除之后软件恢复正常。

建议软件启动可以跳过权限不正确、配置不正确的文件，然后日志中能提示。

### Environment

```markdown
HertzBeat version(s):v1.3.1
```

### Debug logs

我碰到一个事件如下：
我的目录权限是非root，但是在进行自定义监控时候，在define目录下面创建了一个root权限的.yml监控示例文件，导致软件无法启动，报错
![5e4d281e60db41ba40cfcac1fab3463](https://github.com/dromara/hertzbeat/assets/10276100/277959df-8bd3-4869-ae51-b80000040c6d)
我删除了这个文件之后，依然无法启动，然后发现还有个隐藏的.yml.swp文件存在，也是root权限，导致无法启动，删除之后软件恢复正常。

建议软件启动可以跳过权限不正确、配置不正确的文件，然后日志中能提示。

### Anything else?

无

**Comment by luoxuanzao** [comment]
I want help

**Comment by l646505418** [comment]
> I want help

feel free to start

**Comment by luoxuanzao** [comment]
Is it to be modified to only record logs, and any exceptions are not thrown

**Comment by l646505418** [comment]
> Is it to be modified to only record logs, and any exceptions are not thrown

From my perspective, you can add logs in your local to track and debug but not push such changes to remote.

**Comment by luoxuanzao** [comment]
> > Is it to be modified to only record logs, and any exceptions are not thrown
> 
> From my perspective, you can add logs in your local to track and debug but not push such changes to remote.

So is it unnecessary to fix this bug?

**Comment by l646505418** [comment]
> > > Is it to be modified to only record logs, and any exceptions are not thrown
> > 
> > 
> > From my perspective, you can add logs in your local to track and debug but not push such changes to remote.
> 
> So is it unnecessary to fix this bug?

I mistake your original meaning, you can do what you want to fix
