### ISSUE TITLE
[BUG] <In the threshold setting, the notification template environment variable display error>

### ISSUE THREAD

**Issue by Kylin-Guo** [dromara/hertzbeat#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在阈值设置中的 通知模版环境变量 显示错误

![图片](https://github.com/dromara/hertzbeat/assets/131239856/f64ce592-a66e-4379-a257-eb8ed05b3750)

### Environment

```markdown
HertzBeat version(s):v1.3.2
```

**Comment by tomsun28** [comment]
hi 你选择了什么阈值指标出现的这种情况

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, what threshold indicator did you choose for this situation?

**Comment by Kylin-Guo** [comment]
> hi 你选择了什么阈值指标出现的这种情况

多谢回复，就目前我这边测试到的情况而言，随便选择一个指标都会出现该情况，只要不是选择“监控可用性”即可

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> hi What threshold indicator did you choose for this situation?

Thank you for your reply. As far as I am currently testing, this situation will occur if you choose any indicator, as long as you do not choose "monitoring availability".

**Comment by tomsun28** [comment]
收到🫡 谢谢反馈，我们处理下

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Received 🫡 Thank you for your feedback, we will deal with it
