### ISSUE TITLE
[BUG] <alarm silence strategy failed>

### ISSUE THREAD

**Issue by Kylin-Guo** [dromara/hertzbeat#1123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在使用告警静默功能测试时，发现以下情况：

周期性静默：

静默失败的情况：1.monitorName   2.monitorID   3.自定义标签   4.告警级别（选择 全部级别 或 单独一个任意级别 皆静默失败）

一次性静默：

静默成功的情况：1.monitorName   2.monitorID   3.自定义标签

静默失败的情况：告警级别（选择 全部级别 或 单独一个任意级别 皆静默失败）

### Environment

```markdown
HertzBeat version(s):v1.3.2
```

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback received 🫡

**Comment by l646505418** [comment]
Hi @tomsun28 ,according to source code, seems only when tag match takes effect , will priority match start checking and matching. I am not very sure is this a design error? 
![silence](https://github.com/dromara/hertzbeat/assets/50475131/b4ae5eaf-77ed-4936-8bf6-a99890d31dd3)

**Comment by Ceilzcx** [comment]
你好，周期性告警静默目前有个bug，默认情况下前端页面选择日期是全部勾选的，但是数据库存进去时days字段是空的，请查询一下数据库表是否和这个bug有关

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hello, there is currently a bug in Periodic Alarm Silence. By default, all dates are selected on the front-end page, but the days field is empty when the database is stored. Please check whether the database table is related to this bug.

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Hello, there is currently a bug in Periodic Alarm Silence. By default, all dates are checked on the front-end page, but the days field is empty when the database is entered. Please check whether the database table is related to this bug.

![Image](https://github.com/dromara/hertzbeat/assets/131239856/12c6efa9-f7b3-4089-9736-c33495f20b0d)

Hello, I have created two new silent rules. As you said, the days field is empty, but the one with id 4 is a periodic silence, and the one with id 5 is one-time silence, and the days field of both is empty.

**Comment by tomsun28** [comment]
> Hi @tomsun28 ,according to source code, seems only when tag match takes effect , will priority match start checking and matching. I am not very sure is this a design error? 

hi @l646505418 i think it is a bug. it will be fixed by pr #1131

**Comment by tomsun28** [comment]
fix by v1.4.0
