### ISSUE TITLE
[Question] <title>Huawei switches need software to support SNMP v3

### ISSUE THREAD

**Issue by Mr-zhou315** [dromara/hertzbeat#1126]
### Question

今天进行华为交换机监控配置发现交换机是SNMP v3版本。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

Today, I performed Huawei switch monitoring configuration and found that the switch is SNMP v3.

**Comment by tomsun28** [comment]
> 还有一个问题就是通用模板监控的oid没有注释，冷门的交换机套用模板会监控异常。

欢迎一起贡献完善注释哇  https://github.com/dromara/hertzbeat/issues/1212
