### ISSUE TITLE
[BUG] <After modifying the yml configuration file, re-refresh or reload or clear the cache, the data before modification is still displayed>

### ISSUE THREAD

**Issue by tonywen1990** [dromara/hertzbeat#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

对在线修改yml体验感较差，修改后缓存很久才能被清掉。
暂时最直观有效的处理办法就是重启服务，然后就生效。

### Environment

```markdown
HertzBeat version(v1.3.2):
```

**Comment by tomsun28** [comment]
🫡 we will fix it.
