### ISSUE TITLE
[BUG] <yml is configured in Chinese, the push cannot get the value>

### ISSUE THREAD

**Issue by tonywen1990** [dromara/hertzbeat#1135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

协议是snmp，选的是linux，通过mib查cpu的使用率。
在yml定义cpu使用率变量为 “使用率”
-filed:使用率
 type:0
 unit:%
oids：
   使用率： 1.3.x.x.x.x.x.x
配置后页面显示正常。
问题：在配置推送的时候，显示当前cpu的使用率，加载不到数据。只显示“当前的值为 : ${使用率}   ”

### Environment

```markdown
HertzBeat version(v1.3.2):
```

**Comment by tomsun28** [comment]
你的这个 `${使用率} `这个指标本身有采集到值吗 建议最好是用英文

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Has your `${Usage Rate}` indicator itself collected any values? It is recommended to use English

**Comment by tonywen1990** [comment]
就是在监控页面能采集到信息，我才去试验推送。然后推送判断能生效，linux.cpu.使用率 &gt;1 触发预警推送。只是推送，拿不到当前的值。这个由来是因为定义的指标默认是英文，在监控页面显示不友好。



发自我的iPhone


------------------ Original ------------------
From: tomsun28 ***@***.***&gt;
Date: Thu,Jul 27,2023 6:03 PM
To: dromara/hertzbeat ***@***.***&gt;
Cc: tonywen1990 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dromara/hertzbeat] [BUG] <yml is configured in Chinese, the pushcannot get the value&gt; (Issue #1135)





 
你的这个 ${使用率} 这个指标本身有采集到值吗 建议最好是用英文

**Comment by tonywen1990** [comment]
发自我的iPhone


------------------ Original ------------------
From: tomsun28 ***@***.***&gt;
Date: Thu,Jul 27,2023 6:03 PM
To: dromara/hertzbeat ***@***.***&gt;
Cc: tonywen1990 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dromara/hertzbeat] [BUG] <yml is configured in Chinese, the pushcannot get the value&gt; (Issue #1135)





 
你的这个 ${使用率} 这个指标本身有采集到值吗 建议最好是用英文

**Comment by tomsun28** [comment]
hi the new version v1.4.1 has solved this.
