### ISSUE TITLE
[Question] <title> ERROR app-undefined.yml  (No such file or directory)

### ISSUE THREAD

**Issue by Mr-zhou315** [dromara/hertzbeat#1139]
### Question

启动软件时候，日志提示这个，对启动没影响，但是为啥要找这个文件。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

When starting the software, the log prompts this, which has no effect on the startup, but why do I need to find this file.

**Comment by tomsun28** [comment]
👍👍 这看起来是个某种情况下导致的bug 后面复现下

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
👍👍 This seems to be a bug caused by a certain situation, and it will be reproduced later

**Comment by tomsun28** [comment]
fix by v1.4.0
