### ISSUE TITLE
[BUG] <Enterprise WeChat push display content is too cumbersome>

### ISSUE THREAD

**Issue by tonywen1990** [dromara/hertzbeat#1141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/dromara/hertzbeat/assets/140680839/3c780838-50dc-4170-8a51-ec1b48d130b8)
企业微信应用推送，显示过多内容。跟微信聊天机械人的推送内容差别太大。
期望：能优化推送内容信息。将参数内容隐藏。

### Environment

```markdown
HertzBeat version(v1.3.2):
```

**Comment by tomsun28** [comment]
Got it, thanks for feedback

**Comment by l646505418** [comment]
> Got it, thanks for feedback

maybe only send the monitorID and alert content?
