### ISSUE TITLE
[BUG] <When there are too many CPUs, the icons on the history monitoring page are not fully displayed>

### ISSUE THREAD

**Issue by tonywen1990** [dromara/hertzbeat#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

<img width="363" alt="123" src="https://github.com/dromara/hertzbeat/assets/140680839/b14487c3-8d25-4958-8091-f9b37b31a2fa">
比如超级服务器，64个cpu。在界面无法显示全，想排查cpu哪个时段比较高。不好排查。
期望：建议优化图表显示。

### Environment

```markdown
HertzBeat version(v1.3.2):
```

**Comment by tomsun28** [comment]
hi, this has fixed in version 1.4.3
