### ISSUE TITLE
[Task] <Development of custom template configuration for message notification>

### ISSUE THREAD

**Issue by Eden4701** [dromara/hertzbeat#1145]
### Description

HertzBeat supports many alarm methods, but the content of message notification is basically solidified and not very extensible, and it is hard-coded in the project through Thymeleaf. In order to meet the various notification needs of different users, we hope to design and implement a notification template management page, which allows users to customize the notification template and choose different templates while selecting the notification method.
Related UI pages：
![image](https://github.com/dromara/hertzbeat/assets/68422437/8bd2aec4-fc4e-43ab-a49a-bbf341a68eea)

### Task List

1. Design a universal template.
2. Design and implement the notification template configuration management page, and users can configure the template on the UI page.
3. The notification template adaptation supports the content of various notification methods such as nailing, WeChat, email, telegram, discord, etc.

**Comment by zqr10159** [comment]
这个需求开源之夏作为学生目标在做了

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This summer of open source needs to be done as a student goal
