### ISSUE TITLE
[BUG] <The platform reports an error after deleting the custom template application>

### ISSUE THREAD

**Issue by chenguibing1** [dromara/hertzbeat#1150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在自定义监控模板那里，删除了模板的注释说明，应用模板后，整个平台报错，无法看到侧边状态栏，平台全局变成英文版，无法切换语言

### Environment

```markdown
HertzBeat version(s): v1.3.2
```

### Debug logs

409:
http://XXXXX:8088/api/apps/h
ierarchy
请求与服务器端目标资源的当前状态相冲突

### Anything else?

无

**Comment by tomsun28** [comment]
谢谢反馈 收到🫡

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback received 🫡
