### ISSUE TITLE
[BUG] error mounting "/opt/application.yml" to rootfs at "/opt/hertzbeat/config/application.yml

### ISSUE THREAD

**Issue by skapytek** [dromara/hertzbeat#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

docker run -d -p 1157:1157     -e TZ=Europe/Berlin     -v /opt/data:/opt/hertzbeat/data     -v /opt/logs:/opt/hertzbeat/logs     -v /opt/application.yml:/opt/hertzbeat/config/application.yml     -v /opt/sureness.yml:/opt/hertzbeat/config/sureness.yml     --name hertzbeat tancloud/hertzbeat
Unable to find image 'tancloud/hertzbeat:latest' locally
latest: Pulling from tancloud/hertzbeat
751ef25978b2: Pull complete
140e22108c7d: Pull complete
993077aca88e: Pull complete
d1a940e1e4e8: Pull complete
fa84f2de330f: Pull complete
91a75a310198: Pull complete
293a30c95b46: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:a657455c3c554544e7d64568a365141e39e64392d3e1ff30759bed1ffec8bfef
Status: Downloaded newer image for tancloud/hertzbeat:latest
9761046bf2565e446d8dbab0249b54894d7dd5c05bb0efb8e97a0a99e67ac137
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/application.yml" to rootfs at "/opt/hertzbeat/config/application.yml": mount /opt/application.yml:/opt/hertzbeat/config/application.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
hi you need download [/script/application.yml](https://github.com/dromara/hertzbeat/raw/master/script/application.yml), [/script/sureness.yml](https://github.com/dromara/hertzbeat/blob/master/script/sureness.yml) first and mounting it. 
Or you can copy the file from docker container

**Comment by tomsun28** [comment]
update the deploy doc https://hertzbeat.com/docs/start/docker-deploy
