### ISSUE TITLE
[BUG] <title> Deleted the monitoring, and the internal request is still scheduled

### ISSUE THREAD

**Issue by wtjperi2003** [dromara/hertzbeat#1167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

springboot新建了个endpoint。然后新建一个自定义的监控，请求这个endpoint。之后我把这个监控删除了，但是发现，springboot项目这里还在定时接受到请求。应该hertzbeat内部定时器没关闭

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
hi, 是哪个版本的hertzbeat，我记得之前老版本会有这个问题

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, which version of hertzbeat is it? I remember that the old version had this problem

**Comment by wtjperi2003** [comment]
> hi, 是哪个版本的hertzbeat，我记得之前老版本会有这个问题

1.3.2

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> hi, which version of hertzbeat is it, I remember that the old version had this problem

1.3.2

**Comment by tomsun28** [comment]
hi 是长时间一直在调度吗 还是说取消后一个采集周期内还在调度，之后就没有调度了。可以稍后我们发布1.4.0试试

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Has hi been scheduled for a long time, or is it still scheduled within one collection cycle after cancellation, and then there is no scheduling. You can try it later when we release 1.4.0

**Comment by wtjperi2003** [comment]
> hi 是长时间一直在调度吗 还是说取消后一个采集周期内还在调度，之后就没有调度了。可以稍后我们发布1.4.0试试

一直再调度。1.4.0出来了，我再试试

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Is hi being scheduled for a long time, or is it still scheduled within one collection cycle after cancellation, and then there is no scheduling. You can try it later when we release 1.4.0

Always reschedule. 1.4.0 is out, I will try again

**Comment by wtjperi2003** [comment]
今天试了，没在重现这个bug，我关了

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I tried it today and the bug didn't reappear. I turned it off.
