### ISSUE TITLE
[Task] [Suggest] Added one-click test monitoring results and export report function

### ISSUE THREAD

**Issue by Suremotoo** [dromara/hertzbeat#1171]
## 建议功能：
在现有的 hertzbeat 项目中，添加一个功能，允许用户根据已添加的监控或配置，**一键测试监控结果**，并能够导出结果报告为 HTML 或 PDF 格式。

## 背景：
在一些场景下，我们可能无法或不方便部署监控服务器来运行 hertzbeat。然而，定期进行服务器运维是必要的，而手动处理这些任务可能会耗费大量时间和精力。通过添加这个功能，用户可以轻松地将 hertzbeat 配置打包为一个运行包或命令工具，从而脱离依赖环境。用户只需将运行包插入运维机器，按需执行监控配置，实现省时省力的运维过程。

## 预期实现：

在 hertzbeat 界面中添加一个 "一键测试" 或类似的按钮。
用户点击该按钮后，hertzbeat 将根据已添加的监控配置执行测试。
测试完成后，用户可以选择导出结果报告，支持导出为 HTML 或 PDF 格式。
这个功能将为用户提供便利，减少手动运维的工作量，当然也增强 hertzbeat 的实用性。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

## Suggested features:
In the existing hertzbeat project, add a function that allows users to **one-click test monitoring results** according to the added monitoring or configuration, and can export the result report to HTML or PDF format.

## background:
In some scenarios, it may not be possible or convenient for us to deploy a monitoring server to run hertzbeat. However, regular server maintenance is necessary, and handling these tasks manually can consume a lot of time and effort. By adding this feature, users can easily package the hertzbeat configuration as a runtime package or command tool, thereby breaking away from the dependent environment. Users only need to insert the running package into the operation and maintenance machine, and perform monitoring configuration on demand, realizing a time-saving and labor-saving operation and maintenance process.

## Expected implementation:

Add a "One Click Test" or similar button to the hertzbeat interface.
After the user clicks the button, hertzbeat will execute the test according to the added monitoring configuration.
After the test is completed, the user can choose to export the result report, which supports exporting to HTML or PDF format.
This feature will provide convenience to users, reduce the workload of manual operation and maintenance, and of course enhance the practicability of hertzbeat.

### Task List

_No response_
