### ISSUE TITLE
[Task] <When importing and exporting monitoring, support export collectors, configure collectors when importing>

### ISSUE THREAD

**Issue by zqr10159** [dromara/hertzbeat#1174]
### Description

当前v1.4.0版本，导出监控没有采集器信息，导入后使用默认采集器，应该在导入时支持配置

### Task List

-[ ]导出监控采集器信息
-[ ]在导入时支持配置采集器

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

In the current version v1.4.0, there is no collector information for export monitoring, and the default collector is used after importing, which should support configuration when importing

### Task List

-[ ]Export monitoring collector information
-[ ]Support configuration collectors during import

**Comment by Ceilzcx** [comment]
确实有问题，你这边修复一下？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
There is indeed a problem, can you fix it here?

**Comment by zqr10159** [comment]
> 确实有问题，你这边修复一下？

ok，我有空看看

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> There is indeed a problem, can you fix it here?

ok, I have time to take a look
