### ISSUE TITLE
[BUG] <The path of the top four columns on the monitoring homepage is wrong>

### ISSUE THREAD

**Issue by tonywen1990** [dromara/hertzbeat#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我只添加了windows监控，打开监控首页最上方的监控。跳转过去是linux监控。
用f12查看a标签，跳转 href=“”/monitors?app=linux“”。路径是被写死了。

### Environment

```markdown
HertzBeat version(s):1.4.0
```

**Comment by tomsun28** [comment]
repeat  https://github.com/dromara/hertzbeat/issues/1076

**Comment by Ceilzcx** [comment]
@tonywen1990 和tom老哥讨论了一下，监控总览可以稳定的跳转，所以把上面四个homepage的a标签删了，上面只是展示不做跳转

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@tonywen1990 Discussed with brother tom, the monitoring overview can jump stably, so I deleted the a tags of the above four homepages, and the above just showed that there is no jump
