### ISSUE TITLE
[BUG] <Monitoring status has not changed>

### ISSUE THREAD

**Issue by Kylin-Guo** [dromara/hertzbeat#1184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

该环境从昨天进行升级测试，已经连续运行24小时，端口采集不到任何信息（正常是会失败的，因为这个端口并没有开放），但监控可用性没有告警，且监控状态显示正常监控

![image](https://github.com/dromara/hertzbeat/assets/131239856/1635cbce-c7eb-4420-8f7b-b183ab47bad9)

PS：V1.3.2测试过，此种情况监控可用性会转变为 不可用

### Environment

```markdown
HertzBeat version(s):v1.4.0
```

**Comment by tomsun28** [comment]
收到🫡

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
received 🫡

**Comment by tomsun28** [comment]
hi 你看下阈值规则那里有对应的默认内置端口可用性阈值吗？是否开启
<img width="1817" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/617681f3-313b-47db-9acd-a77fe71f8c9c">

**Comment by Kylin-Guo** [comment]
> hi 你看下阈值规则那里有对应的默认内置端口可用性阈值吗？是否开启 <img alt="image" width="1817" src="https://user-images.githubusercontent.com/24788200/260657245-617681f3-313b-47db-9acd-a77fe71f8c9c.png">

这里没有这些可用性告警规则，但应该不影响监控状态的转变不是吗？阈值的作用应该是体现在告警中心里面吧

（不过我也好奇为什么我手头上这个测试环境从v1.3.0升级上来的时候没有自动创建这些规则，但另外一台服务器倒是有正常插入这些规则

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> hi Have you checked the threshold rules and is there a corresponding default built-in port availability threshold? Whether to enable <img alt="image" width="1817" src="https://user-images.githubusercontent.com/24788200/260657245-617681f3-313b-47db-9acd-a77fe71f8c9c.png">

There are no such availability alert rules here, but it should not affect the transition of the monitoring state, should it? The function of the threshold should be reflected in the alarm center.

(However, I am also curious why these rules were not automatically created when the test environment on hand was upgraded from v1.3.0, but another server inserted these rules normally

**Comment by tomsun28** [comment]
> 这里没有这些可用性告警规则，但应该不影响监控状态的转变不是吗？阈值的作用应该是体现在告警中心里面吧


影响的，可用性状态是根据可用性告警来变更的  需要有这些规则。你是不是设置手动执行的SQL而不是系统自动创建数据表导致的没有这些规则

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> There are no these availability alert rules here, but it should not affect the transition of monitoring status, right? The function of the threshold should be reflected in the alarm center.


Affected, the availability status is changed based on availability alerts These rules are required. Did you set the manual execution of SQL instead of the system automatically creating data tables, so there are no such rules

**Comment by Kylin-Guo** [comment]
> > 这里没有这些可用性告警规则，但应该不影响监控状态的转变不是吗？阈值的作用应该是体现在告警中心里面吧
> 
> 影响的，可用性状态是根据可用性告警来变更的 需要有这些规则。你是不是设置手动执行的SQL而不是系统自动创建数据表导致的没有这些规则

原来如此，谢谢。但我是默认自动插入SQL的

那我可能知道为何没有插入阈值规则的原因了，可能是因为在 1.3.2 之前的版本数据库连接的方法相比于 1.3.2 有改动？不知道您是否有印象，在1.3.1时我曾提出过一个 PR 是针对 hibernate 的配置方法的，后面在 1.3.2 版本时因为有问题，所以又有小伙伴修改了一次

![image](https://github.com/dromara/hertzbeat/assets/131239856/4940f0be-18ec-4936-9c86-f01207adfc10)

上图是我当前环境的配置文件，在 1.3.2 之前版本，MySQL的IP可以直接填写容器名，1.3.2 版本突然不行了，会报找不到主机，需要改为填IP地址。现在 1.4.0 使用容器名又正常了，我认为可能与外部数据库的连接方法有更改所导致。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > There are no availability alert rules here, but it should not affect the transition of monitoring status, right? The function of the threshold should be reflected in the alarm center.
>
> Affected, the availability state is changed based on availability alerts These rules are required. Did you set the manual execution of SQL instead of the system automatically creating data tables, so there are no such rules

That's right, thank you. But I automatically insert SQL by default

Then I may know why the threshold rule is not inserted, maybe because the method of database connection in versions before 1.3.2 has changed compared to 1.3.2? I don’t know if you have the impression, but in 1.3.1, I proposed a PR for hibernate’s configuration method. Later, in version 1.3.2, there was a problem, so another friend modified it once.

![image](https://github.com/dromara/hertzbeat/assets/131239856/4940f0be-18ec-4936-9c86-f01207adfc10)

The picture above is the configuration file of my current environment. Before version 1.3.2, the MySQL IP can directly fill in the container name. The version 1.3.2 suddenly fails. It will report that the host cannot be found, and you need to fill in the IP address instead. Now 1.4.0 uses the container name normally again, I think it may be caused by a change in the connection method with the external database.

**Comment by tomsun28** [comment]
> 那我可能知道为何没有插入阈值规则的原因了，可能是因为在 1.3.2 之前的版本数据库连接的方法相比于 1.3.2 有改动？不知道您是否有印象，在1.3.1时我曾提出过一个 PR 是针对 hibernate 的配置方法的，后面在 1.3.2 版本时因为有问题，所以又有小伙伴修改了一次

👍 是的这里 需要 jpa hibernate ddl-auto: update 为true 才会自动新建表结构

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Then I may know the reason why the threshold rule is not inserted, maybe because the method of database connection in versions before 1.3.2 has changed compared to 1.3.2? I don’t know if you have the impression, but in 1.3.1, I proposed a PR for the configuration method of hibernate. Later, in version 1.3.2, because there was a problem, another small partner modified it once.

👍 Yes here, you need jpa hibernate ddl-auto: update to be true to automatically create a new table structure

**Comment by Kylin-Guo** [comment]
> > 那我可能知道为何没有插入阈值规则的原因了，可能是因为在 1.3.2 之前的版本数据库连接的方法相比于 1.3.2 有改动？不知道您是否有印象，在1.3.1时我曾提出过一个 PR 是针对 hibernate 的配置方法的，后面在 1.3.2 版本时因为有问题，所以又有小伙伴修改了一次
> 
> +1 是的这里 需要 jpa hibernate ddl-auto: update 为true 才会自动新建表结构

谢谢，我会关掉这个issue

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > Then I may know why the threshold rule is not inserted, maybe because the method of database connection in versions before 1.3.2 has changed compared to 1.3.2? I don’t know if you have the impression, but in 1.3.1, I proposed a PR for hibernate’s configuration method. Later, in version 1.3.2, there was a problem, so another friend modified it once.
>
> +1 Yes, here jpa hibernate ddl-auto: update is required to be true to automatically create a new table structure

Thanks, I will close this issue
