### ISSUE TITLE
td数据库入库不全

### ISSUE THREAD

**Issue by mangel2002** [dromara/hertzbeat#119]
![image](https://user-images.githubusercontent.com/9348020/167521365-f960103c-d167-405a-9c15-3ab2c80936fa.png)
配置了100个左右监控，采集日志都有。但是有一半左右没有入库。造成监控历史图表不全。

**Comment by tomsun28** [comment]
hi, the version [hertzbeat v1.0](https://github.com/dromara/hertzbeat/releases/tag/v1.0) has fix it
