### ISSUE TITLE
[Question] <About managing collector cluster management>

### ISSUE THREAD

**Issue by Kylin-Guo** [dromara/hertzbeat#1194]
### Question

在使用过程中会出现想要删除采集器集群重新注册，或同一个采集器集群名字更换机器进行注册、限定某个集群的调度任务数量上下限等等，但目前没有在Web页面中找到管理配置采集器集群的地方。

请问现在想要删除采集器集群是否只能够直接删除hzb_collector表中的数据？有没有考虑过加上删除集群和管理集群等功能？

**Comment by tomsun28** [comment]
hi 是的我们有这个计划做采集器集群管理页面，支持采集器主动删除，主动下线，列表查看等

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi Yes, we have this plan to build a collector cluster management page, which supports active deletion of collectors, active offline, list viewing, etc.
