### ISSUE TITLE
[Question] <Threshold alarm recovery notification>

### ISSUE THREAD

**Issue by Kylin-Guo** [dromara/hertzbeat#1206]
### Question

目前HertzBeat的告警恢复通知，当监控可用性发生变化时才会发出，但对于阈值变化恢复时没有相对应的恢复通知

例如监控主机资源的CPU使用情况时，若设置的阈值为CPU使用率的80%，在某个时刻点超过了阈值导致告警，一个小时后回落到正常水平时，只发出一条 CPU使用率告警的通知，机器是否恢复正常只有后台管理员或机器的运维人员才能得知

请问是否有计划添加相关功能？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

At present, HertzBeat's alarm recovery notification will only be issued when the monitoring availability changes, but there is no corresponding recovery notification for the recovery of the threshold change

For example, when monitoring the CPU usage of host resources, if the set threshold is 80% of the CPU usage, an alarm is generated when the threshold is exceeded at a certain point, and only one CPU usage alarm is issued when it falls back to the normal level after an hour. Notification, whether the machine is back to normal can only be known by the background administrator or the operation and maintenance personnel of the machine

Is there any plan to add related functions?

**Comment by Kylin-Guo** [comment]
Sorry，已看见在阈值设置中新增了恢复通知选项

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Sorry, I have seen that the recovery notification option has been added to the threshold settings
