### ISSUE TITLE
告警查询一个问题

### ISSUE THREAD

**Issue by mangel2002** [dromara/hertzbeat#121]
1、问题1.不好截图就描述下吧，就是告警如果分多个页。查询选择“未处理”的项后。选择当前页全部处理。后边几页还有未出确认的。这时候再过滤搜索未处理就不能显示了。

**Comment by tomsun28** [comment]
hi 谢谢反馈 此问题和这个比较像 https://github.com/dromara/hertzbeat/issues/91 已经修复，会在下一版本发出

**Comment by tomsun28** [comment]
hi this bug is solved by #97
