### ISSUE TITLE
取消监控项一个问题

### ISSUE THREAD

**Issue by mangel2002** [dromara/hertzbeat#122]
如果设置一个ping 每10秒ping一个不通的地址。这样会持续出现多个告警。此时取消这个监控。但是采集告警还会持续。持续多久没有试过。每次重启服务可能会恢复。

**Comment by tomsun28** [comment]
👍 我们复现下这个

**Comment by tomsun28** [comment]
hi this fix by pr #215 , will be publish in v1.1.1
