### ISSUE TITLE
[Task] <title>Threshold rule function has no query condition

### ISSUE THREAD

**Issue by liuweih** [dromara/hertzbeat#1230]
### Description

阈值规则预制有60多个，但没有查询条件，不方便使用，可以完善一下

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

There are more than 60 prefabricated threshold rules, but there is no query condition, which is inconvenient to use. It can be improved

### Task List

_No response_
