### ISSUE TITLE
[BUG] 1.4.0 version configuration Feishu robot alarm error

### ISSUE THREAD

**Issue by xflcx1991** [dromara/hertzbeat#1232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

类似 #976 ，看到写了bug，但是又关闭issue了。现在在1.4.0版本仍有这个问题 
![image](https://github.com/dromara/hertzbeat/assets/3775351/4312ed45-bbf1-4893-9f61-497d2303d62b)

### Expected Behavior

如同选择webhook方式那样成功生效

### Environment

```markdown
HertzBeat version(s):V1.4.0
```

### Debug logs

后台没有日志变化

**Comment by tomsun28** [comment]
hi 那里填飞书机器人KEY 而不是URL，KEY是URL最后面那一部分 https://hertzbeat.com/zh-cn/docs/help/alert_feishu/

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi, fill in the Feishu robot KEY instead of the URL, and the KEY is the last part of the URL https://hertzbeat.com/zh-cn/docs/help/alert_feishu/

**Comment by xflcx1991** [comment]
> hi 那里填飞书机器人KEY 而不是URL，KEY是URL最后面那一部分 https://hertzbeat.com/zh-cn/docs/help/alert_feishu/

我的天，我的阅读理解问题。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Hi, fill in the Feishu Robot KEY instead of the URL. The KEY is the last part of the URL https://hertzbeat.com/zh-cn/docs/help/alert_feishu/

OMG I have reading comprehension issues.
