### ISSUE TITLE
The home page lacks the overall switch monitoring indicator

### ISSUE THREAD

**Issue by tonywen1990** [dromara/hertzbeat#1235]
### Question

希望增加一个交换机总体指标在首页显示

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

I hope to add a switch overall indicator to display on the home page
