### ISSUE TITLE
[BUG] <The alarm still exists after canceling monitoring>

### ISSUE THREAD

**Issue by liuweih** [dromara/hertzbeat#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

数据库监控异常，取消后还在报警，把配置删除后仍在报警，服务重启仍报警

### Environment

```markdown
HertzBeat version(s):1.4.0
```

**Comment by tomsun28** [comment]
hi the new version v1.4.1 has solved.
