### ISSUE TITLE
[BUG] <Error in counting the number of tasks of the main page collector>

### ISSUE THREAD

**Issue by Kylin-Guo** [dromara/hertzbeat#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

部署采集器后：
![图片](https://github.com/dromara/hertzbeat/assets/131239856/47db54aa-9366-454a-b5dd-c9a0513ba8e0)

删除采集器后：
![图片](https://github.com/dromara/hertzbeat/assets/131239856/582cbf48-71ab-43e7-bbcf-146006425a92)

### Environment

```markdown
HertzBeat version(s):v1.4.1
```

**Comment by tomsun28** [comment]
hi 👍 the newest refresh docker images / package has solved it.
