### ISSUE TITLE
建议处理日志中IP、账号与密码等敏感信息

### ISSUE THREAD

**Issue by goo-kits** [dromara/hertzbeat#128]
![image](https://user-images.githubusercontent.com/13163673/168514519-fff05dde-730a-49b6-a719-ef1d1b00fe63.png)

**建议日志中针对IP、账号与密码等敏感信息做模糊处理**
当前控制台日志和日志文件中，系统监控模块中的服务器IP、账号与密码均明文显示，是严重的安全风险，建议迷糊处理，或者采用对数据取hash值作为存储键。

**Comment by wang1027-wqh** [comment]
收到，不错的建议thanks，我们后续马上处理

**Comment by wang1027-wqh** [comment]
> ![image](https://user-images.githubusercontent.com/13163673/168514519-fff05dde-730a-49b6-a719-ef1d1b00fe63.png)
> 
> **建议日志中针对IP、账号与密码等敏感信息做模糊处理** 当前控制台日志和日志文件中，系统监控模块中的服务器IP、账号与密码均明文显示，是严重的安全风险，建议迷糊处理，或者采用对数据取hash值作为存储键。

收到，不错的建议，thanks，我们会尽快修复

**Comment by tomsun28** [comment]
hi, the version [hertzbeat v1.0](https://github.com/dromara/hertzbeat/releases/tag/v1.0) has suppouted this
