### ISSUE TITLE
[BUG] <handle todo about remoting await server and client start>

### ISSUE THREAD

**Issue by Ceilzcx** [dromara/hertzbeat#1280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/dromara/hertzbeat/assets/48920254/100941a9-9769-4f3b-9362-138e7188025a)
sometimes maybe client start above 1 second, and cause error

### Environment

```markdown
HertzBeat version(s): 1.4.1
```

**Comment by misselvexu** [comment]
It makes more sense to use a combination of semaphore waits and `server & client startup state` judgments here ?

**Comment by Ceilzcx** [comment]
> It makes more sense to use a combination of semaphore waits and `server & client startup state` judgments here ?

我不太了解你的想法，信号量打算如何使用，是否可以提交一个pr或者简单描述一下你的思路？
