### ISSUE TITLE
[Task] It is recommended to add presets for emqx monitoring indicators

### ISSUE THREAD

**Issue by m01i0ng** [dromara/hertzbeat#1290]
### Description

https://www.emqx.io/docs/zh/v5.0/observability/overview.html
上面是文档，emqx 在 物联网 mqtt 这块应用还是挺广泛的、

**Comment by vinci-897** [comment]
done

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
done

**Comment by vinci-897** [comment]
done
