### ISSUE TITLE
深颜色主题下的BUG

### ISSUE THREAD

**Issue by ConradWen** [dromara/hertzbeat#133]
在主题为深颜色的时候，填写新增接收人时出现了输入遮挡的bug
![图片](https://user-images.githubusercontent.com/69459423/169237177-98d6e795-fb34-44c3-9c45-795d3f6fc8bc.png)
浅颜色主题没有这个问题
![图片](https://user-images.githubusercontent.com/69459423/169237296-8758a008-66b2-4c24-a5b8-1a0c036306c3.png)

希望尽快实现网络设备的监控，那可就太完美了呀！！加油！

**Comment by tomsun28** [comment]
thanks 我们准备下一版解决

**Comment by tomsun28** [comment]
hi, the version [hertzbeat v1.0](https://github.com/dromara/hertzbeat/releases/tag/v1.0) has fix it
