### ISSUE TITLE
v1.4.2 docker version history indicator query cannot find indicator records for more than 1 day

### ISSUE THREAD

**Issue by rbsrcy** [dromara/hertzbeat#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

检查该监控对应TDengine数据库表，发现近7天的数据是存在的，但是页面上查询不出来。
![1](https://github.com/dromara/hertzbeat/assets/4798540/4bdeba7d-7380-4fa5-b2d6-93cc467aaf6b)

![2](https://github.com/dromara/hertzbeat/assets/4798540/6226b5e3-1e53-4545-97f0-b6cf9feadfbc)

### Expected Behavior

能查询1天以上的数据并显示出来

### Environment

```markdown
HertzBeat version(s):v1.4.2
```

### Debug logs

日志无报错

**Comment by tomsun28** [comment]
因为tdengine的处理SQL在 1.4.2 版本更新了下，导致之前的数据查询不到

```
INSERT_TABLE_DATA_SQL = "INSERT INTO %s USING %s TAGS (%s) VALUES %s"

"SELECT ts, instance, `%s` FROM %s WHERE instance = '%s' AND ts >= now - %s order by ts desc"
```
变更为 
```
INSERT_TABLE_DATA_SQL = "INSERT INTO `%s` USING `%s` TAGS (%s) VALUES %s";

"SELECT ts, instance, `%s` FROM `%s` WHERE instance = '%s' AND ts >= now - %s order by ts desc"
```

现在`%s` 修饰了表名，这样有可能之前建的表不识别, 建议手动修改老表

**Comment by jiashu1024** [comment]
![image](https://github.com/dromara/hertzbeat/assets/67859663/37bed75a-7809-41e6-bfe3-ce3c359af7da)
![image](https://github.com/dromara/hertzbeat/assets/67859663/eb9ebfd5-6066-42e7-8944-6049525545cc)
我用的也是1.4.2的版本，刚从 iotdb 切换到 tdengine，我是一点数据都没有。
<img width="1147" alt="image" src="https://github.com/dromara/hertzbeat/assets/67859663/461d9b19-41fd-4a12-b3a4-9fe1adc03247">
