### ISSUE TITLE
[Question] <title>The format of the alarmId value in the alarm message is incorrect and the message cannot be sent.

### ISSUE THREAD

**Issue by tengfei-wu** [dromara/hertzbeat#1333]
### Question

我在使用最新版本（v1.4.2）测试告警时发现个问题，我使用的webhook接口，钉钉无法收到告警信息。排查如下：
查看webhook服务的log，发现告警信息确实可以收到，但是信息中alarmId数值不对，如：alarmId：2,104，正确格式应该是2104。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

I found a problem when using the latest version (v1.4.2) to test the alarm. The webhook interface I used, DingTalk could not receive the alarm information. The troubleshooting is as follows:
Check the log of the webhook service and find that the alarm information can indeed be received, but the alarmId value in the information is incorrect, such as: alarmId: 2,104. The correct format should be 2104.
