### ISSUE TITLE
[BUG] Query time for databases (mysql, mariadb...) should support comparison operations

### ISSUE THREAD

**Issue by Clownsw** [dromara/hertzbeat#1362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I saw that the current type of query_time is 1 (string). If it is switched to 0 (integer), the platform will display wrong data. I think a new type should be added to support

### Environment

```markdown
HertzBeat version(s): laster
```

**Comment by tomsun28** [comment]
> I can fix this if I can

welcome👍👍
