### ISSUE TITLE
告警通知策略中，过滤标签只能设置一个，无法设置多个过滤标签

### ISSUE THREAD

**Issue by daqianxiaoyao** [dromara/hertzbeat#138]
v1.0-beta8中
告警通知策略中，过滤标签只能设置一个，无法设置多个过滤标签

![1653113700(1)](https://user-images.githubusercontent.com/105963325/169638612-3369f745-9c1e-4196-b53b-dd3ca84713f4.png)

![1653113753(1)](https://user-images.githubusercontent.com/105963325/169638650-9c00709e-a4e8-42e1-8a78-48016a750502.png)

**Comment by tomsun28** [comment]
thanks 收到 我们尽快fix

**Comment by tomsun28** [comment]
hi, the version [hertzbeat v1.0](https://github.com/dromara/hertzbeat/releases/tag/v1.0) has fix it
