### ISSUE TITLE
[Task] When adding tags in tag management, random colors are given by default.

### ISSUE THREAD

**Issue by m01i0ng** [dromara/hertzbeat#1386]
### Description

标签量比较大的话选颜色是一个头疼的问题，可以默认随机一个颜色
<img width="1017" alt="image" src="https://github.com/dromara/hertzbeat/assets/19723234/4b7f8c9a-a915-4d95-b0bf-7cf494831559">

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

If the number of labels is relatively large, choosing a color is a headache. You can default to a random color.
<img width="1017" alt="image" src="https://github.com/dromara/hertzbeat/assets/19723234/4b7f8c9a-a915-4d95-b0bf-7cf494831559">


### Task List

_No response_

**Comment by prolevel1** [comment]
I would like to help

**Comment by tomsun28** [comment]
> I would like to help

welcome. this has assigned to you. 
suggest edit code here.  https://github.com/dromara/hertzbeat/blob/master/web-app/src/app/routes/setting/tags/tags.component.ts#L149
add```this.tag.color = randomxxx``` when add a new tag

**Comment by prolevel1** [comment]
Hi @tomsun28 please review this PR: #1412

**Comment by tomsun28** [comment]
> Hi @tomsun28 please review this PR: #1412

ok👍👍
