### ISSUE TITLE
告警中心已处理的故障，其状态能够自动变为已处理，不需要手动更改为已处理

### ISSUE THREAD

**Issue by daqianxiaoyao** [dromara/hertzbeat#139]
在告警恢复之后，原来的故障告警信息还是显示未处理
![1653116133(1)](https://user-images.githubusercontent.com/105963325/169639932-f711db0e-088a-4f80-ade3-2215834d2dd9.png)
而在首页的告警分布也一直显示告警信息
![1653116320(1)](https://user-images.githubusercontent.com/105963325/169639992-f581912f-d7b2-488b-a75c-5a04b6c7ff6a.png)
要想消除这些告警信息，需要在告警中心选择未处理状态的的信息 手动改为已处理。

**Comment by wang1027-wqh** [comment]
I will implement this feature in the future
