### ISSUE TITLE
[Task] <support monitoring dns server metrics>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1397]
### Description

support monitoring dns server metrics, available and more

### Task List

- [ ] support monitoring dns server metrics
- [ ] add help doc

**Comment by Calvin979** [comment]
I would like to help!

**Comment by Calvin979** [comment]
@tomsun28 Thanks for your suggestion. I know how to collect dns server metrics! 
 `dnsjava` is the library I use in my demo as well.

**Comment by Calvin979** [comment]
#1416

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
#1416

**Comment by a-little-fool** [comment]
> I would like to help!



> @tomsun28 Thanks for your suggestion. I know how to collect dns server metrics! `dnsjava` is the library I use in my demo as well.

您好，我想借鉴一下您的代码思路，可以向您咨询一些问题吗🫣
