### ISSUE TITLE
网站监控因默认User-Agent被应用拦截

### ISSUE THREAD

**Issue by lidonvin** [dromara/hertzbeat#14]
网站监控添加应用时，因默认User-Agent被应用拦截，报403。

**Comment by tomsun28** [comment]
宝塔等防火墙默认设置了对请求header中User-Agent=Apache-HttpClient的拦截  
下一版修改hertzbeat的http请求的User-Agent的默认请求头，模拟chrome浏览器

**Comment by wang1027-wqh** [comment]
已经修复
