### ISSUE TITLE
[Task] The problem of alarm triggering and recovery time in the same alarm information

### ISSUE THREAD

**Issue by tengfei-wu** [dromara/hertzbeat#1405]
### Question

我在使用HertzBeat中发现如下问题：
当前模板无论是触发告警还是恢复告警，都只是给出一个时间，这个有时候根本不知道哪个是哪个几点触发的。我希望同一个告警触发和恢复时间做个关联，这样当一个告警信息发出时，信息中会显示此告警触发的时间，当这个告警恢复时，信息中应显示此告警触发和恢复的时间，便于使用者更好区分不同时段的告警信息（如附件所显示的）。附件中是我使用prometheus时收到的告警恢复信息：
<img width="154" alt="prometheus-alertinfo" src="https://github.com/dromara/hertzbeat/assets/74173328/95a64b46-7977-4e16-a48d-fb415e1937a8">

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I'd like to help!

**Comment by Calvin979** [comment]
Hi, @tomsun28 
我改了对应的告警恢复时间，效果如下图所示：
![image](https://github.com/dromara/hertzbeat/assets/131688897/ded5c587-3358-4bc2-89fa-afeeb9d259c5)

对应的告警email:
![image](https://github.com/dromara/hertzbeat/assets/131688897/a2e1e988-b59c-4d65-928d-2820649eaf63)

对应的告警恢复email:
![image](https://github.com/dromara/hertzbeat/assets/131688897/97aad9cd-9880-4ffb-88c5-50e1d19fbeb1)


现在还有一个问题：是否有办法测试剩余的其他所有告警通知。我检查了下，告警通知很多——钉钉、华为云、飞书、企微、telegram等等……这些该如何测试？还是说用单元测试就可以了

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, @tomsun28
I changed the corresponding alarm recovery time, and the effect is as shown below:
![image](https://github.com/dromara/hertzbeat/assets/131688897/ded5c587-3358-4bc2-89fa-afeeb9d259c5)

Corresponding alarm email:
![image](https://github.com/dromara/hertzbeat/assets/131688897/a2e1e988-b59c-4d65-928d-2820649eaf63)

Corresponding alarm recovery email:
![image](https://github.com/dromara/hertzbeat/assets/131688897/97aad9cd-9880-4ffb-88c5-50e1d19fbeb1)


Now there is a question: is there a way to test all other remaining alert notifications. I checked and found a lot of alarm notifications - DingTalk, Huawei Cloud, Feishu, Qiwei, telegram, etc... How should I test these? Or just use unit testing?

**Comment by tomsun28** [comment]
@Calvin979 👍👍 hi 元旦快乐，不用每个都实际环境测试一遍，我们保证在代码debug那里看到的渲染内容OK就行，因为都是用的freemarker模版渲染的

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@Calvin979 👍👍 hi Happy New Year, there is no need to test each one in the actual environment, we ensure that the rendering content seen in the code debug is OK, because they are all rendered using the freemarker template

**Comment by Calvin979** [comment]
@tomsun28 元旦快乐！对应的PR是这个
#1464

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@tomsun28 Happy New Year! The corresponding PR is this
#1464
