### ISSUE TITLE
Test connection failed

### ISSUE THREAD

**Issue by zhengweisk** [dromara/hertzbeat#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

网站监控
直接
测试连接失败
![image](https://github.com/dromara/hertzbeat/assets/1125580/0def0c26-4f2f-46c8-a0df-c400361184be)

### Expected Behavior

无

### Steps To Reproduce

无

### Environment

```markdown
HertzBeat version(s):

docker 运行

1.4.3版本
```

### Debug logs

无日志

### Anything else?

无

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This problem has not been reproduced. Other user environments are normal. Connect refused is usually caused by network problems. Please check the network.
