### ISSUE TITLE
能够自定义故障报警的次数（微信、钉钉等）

### ISSUE THREAD

**Issue by daqianxiaoyao** [dromara/hertzbeat#141]
目前，出现故障后，企业微信会一直报警，直到处理了故障，报警才会结束。
建议增加一个功能：能够自己定义，当出现故障后，微信等报警的次数

**Comment by macaty** [comment]
增加降噪方式，比如连续多少次才报警

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Add noise reduction methods, such as how many times in a row before calling the police

**Comment by macaty** [comment]
或者连续多少分钟异常，再报警
如果上次也是异常，且已经报警过了，就不用
如果上次是正常的，本次已经出发，就需要告警

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Or how many minutes in a row is abnormal, and then call the police
If it was also abnormal last time and the alarm has been reported, there is no need to
If it was normal last time and this time has already started, you need to warn

**Comment by tomsun28** [comment]
已支持告警收敛功能，重复告警在设置的一段时间收敛只发一次

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The alarm convergence function has been supported. Repeated alarms will be converged within a set period of time and will only be sent once.
