### ISSUE TITLE
[BUG] <Availability alarms that have been modified or deleted will be re-added with version updates>

### ISSUE THREAD

**Issue by Kylin-Guo** [dromara/hertzbeat#1433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 在v1.4.2之前，修改过HTTP API的可用性告警描述
2. 更新到v1.4.2后，发现多了一条HTTP API可用性告警规则，删除了第一条默认添加的API可用性告警，再次搜索后发现两条规则都被删除（没有截图，sorry）
3. 更新到v1.4.3之后，发现两条告警规则都被添加回来
![3](https://github.com/dromara/hertzbeat/assets/131239856/e9ae4c51-a87d-4d39-982d-ad394fc966bb)

注：使用的数据库为MySQL8.0.32。可能是因为告警名一致，SQL就一并删除了？此情况利用表主键应该可以解决？

### Environment

```markdown
HertzBeat version(s):v1.4.3
```

**Comment by Kylin-Guo** [comment]
补充说明：当有两条HTTP API可用性告警时，告警信息发出使用的是修改过描述的规则。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Supplementary note: When there are two HTTP API availability alarms, the alarm information is issued using the rules with modified descriptions.

**Comment by tomsun28** [comment]
hi 可用性告警是系统内置强需要的，如果重启系统发现没有一条这个监控类型对应的可用性告警，会自动生成一条，如果存在或者修改则不会。如果确实不想用这条阈值，可以不启用来关闭他。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi Availability alarms are a strong requirement built into the system. If you restart the system and find that there is no availability alarm corresponding to this monitoring type, it will automatically generate one. If it exists or is modified, it will not. If you really don't want to use this threshold, you can disable it by disabling it.

**Comment by Kylin-Guo** [comment]
> hi 可用性告警是系统内置强需要的，如果重启系统发现没有一条这个监控类型对应的可用性告警，会自动生成一条，如果存在或者修改则不会。如果确实不想用这条阈值，可以不启用来关闭他。

Hi，我重新试过，修改可用性告警里面的通知模板内容，修改完之后重启程序
测试结果是：修改告警的通知模板内容，亦会添加一条新的记录
![图片](https://github.com/dromara/hertzbeat/assets/131239856/b78a6130-6b66-40f5-b5a3-938622b90d46)
![图片](https://github.com/dromara/hertzbeat/assets/131239856/f734d1dd-79e5-4215-8f00-c5f8509495b1)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> hi Availability alarms are a strong requirement built into the system. If you restart the system and find that there is no availability alarm corresponding to this monitoring type, it will automatically generate one. If it exists or is modified, it will not. If you really don't want to use this threshold, you can disable it by disabling it.

Hi, I tried again, modified the notification template content in the availability alarm, and restarted the program after modification.
The test result is: modifying the content of the alarm notification template will also add a new record
![Picture](https://github.com/dromara/hertzbeat/assets/131239856/b78a6130-6b66-40f5-b5a3-938622b90d46)
![Picture](https://github.com/dromara/hertzbeat/assets/131239856/f734d1dd-79e5-4215-8f00-c5f8509495b1)

**Comment by tomsun28** [comment]
> 测试结果是：修改告警的通知模板内容，亦会添加一条新的记录

👍收到 我们去修复处理下

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> The test result is: modifying the content of the alarm notification template will also add a new record

👍Received, we will repair it
