### ISSUE TITLE
[BUG] < error executing freemaker template>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在阈值规则中配置linux文件系统使用率大于70，告警中心会消息，但不会发送消息通知。
其他可用性和响应时间规则都能发送消息通知。我使用的是webhook。
log中显示
error freemaker.runtime line 60 - error executing freemaker template
freemaker.core.invalidreferenceException:the following has evaluated to null or missing:
==> value i template freemakertemplate at line 12,column 20

### Expected Behavior

在阈值规则中配置linux文件系统使用率大于70，能调用webhook发送消息通知。

### Environment

```markdown
HertzBeat version(s): v1.4.3

![image](https://github.com/dromara/hertzbeat/assets/24788200/495f7129-5aaf-4a84-a523-cab5d4d173b8)
```

**Comment by tomsun28** [comment]
from gitee issue https://gitee.com/dromara/hertzbeat/issues/I8QOM8#note_23894828

**Comment by Calvin979** [comment]
I can fix this issue

**Comment by Calvin979** [comment]
#1474

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
#1474
