### ISSUE TITLE
[Suggestion] Target Host support hostname entry

### ISSUE THREAD

**Issue by ldysdu** [dromara/hertzbeat#1452]
### Description

Monitor Target Host now only support ipv4, ipv6 and domain name entries. 
But in some situations, we only have the hostname of a target, which has no dot in the string.

Can we change the DOMAIN_SCHEMA pattern to support hostnames?

a working regex pattern is ^[-_a-zA-Z0-9\.]{0,99}$
i can create a pr if needed

**Comment by tomsun28** [comment]
👍👍 Hi, this is indeed. very welcome help us modify code and submit PR
