### ISSUE TITLE
[Feature Issue] Hello, is it possible to add custom modifications that support modifying the corporate WeChat interface address?

### ISSUE THREAD

**Issue by skywlakerliu** [dromara/hertzbeat#1457]
### Question

我们自己有一套内网企业微信接口，不同于外网的地址，可否增加支持？谢谢

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

We have our own internal enterprise WeChat interface, which is different from the external network address. Can we add support? Thank you

**Comment by zqr10159** [comment]
Hi，最新的1.5.0版本已在yml中支持自定义配置 #1535

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, the latest 1.5.0 version supports custom configuration in yml #1535
