### ISSUE TITLE
[BUG] <search monitors error when pageable>

### ISSUE THREAD

**Issue by Mr-zhou315** [dromara/hertzbeat#1470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![1704279015945](https://github.com/dromara/hertzbeat/assets/10276100/45e38295-69f1-4d99-a894-22db9b9cba9b)
发现一个bug  你这里的搜索  点击一次就是搜一次  再点击搜索  直接就不知道是什么过滤  就没东西了  然后也清不了  清空过滤词点搜索  不显示了  

### Environment

```markdown
HertzBeat version(s):
```

**Comment by avvCode** [comment]
i would like to try it
