### ISSUE TITLE
[Task] <refactor freeMakerTemplate render notice template>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1477]
### Description

refactor freeMakerTemplate render notice template.
now, we will create freeMakerTemplate instance everytimes, consider reuse it single instance. 

org.dromara.hertzbeat.manager.component.alerter.impl.AbstractAlertNotifyHandlerImpl#renderContent

**Comment by oyiyou** [comment]
take tihs issue for me please

**Comment by oyiyou** [comment]
https://github.com/dromara/hertzbeat/pull/1483
