### ISSUE TITLE
[Task] <add new field `description` in hertzbeat `tag` detail>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1482]
### Description

add new field `description` in hertzbeat `tag` detail

`description  varchar(255)`
```
DROP TABLE IF EXISTS  hzb_tag ;
CREATE TABLE  hzb_tag
(
    id           bigint           not null auto_increment,
    name         varchar(100)     not null,
    `value`      varchar(100),
    type         tinyint   not null default 0,
    color        varchar(100),
    description  varchar(255),
    creator      varchar(100),
    modifier     varchar(100),
    gmt_create   timestamp        default current_timestamp comment 'create time',
    gmt_update   datetime         default current_timestamp on update current_timestamp comment 'update time',
    primary key (id),
    unique key unique_tag (name, `value`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;
```

### Task List

- [ ] add new field `description` in hertzbeat `tag` detail
- [ ] can add , edit `tag description` in webui

**Comment by GEM0816g** [comment]
i would like to try it

**Comment by tomsun28** [comment]
@GEM0816g 👍👍welcome, has assigned to you.

**Comment by GEM0816g** [comment]
I encountered a problem in the front-end(前端)
![1705241174679](https://github.com/dromara/hertzbeat/assets/85116017/de7c1e83-0203-48d8-b134-d500dd882cb6)
 I have added fields and displayed them, but it seems to be ineffective. I didn't seem to find the right place. May I ask where this was rendered (my front-end is very poor)
And here
![1705241558550](https://github.com/dromara/hertzbeat/assets/85116017/cc7bcbfa-a273-4526-a036-c550554a8a4e)

But it can be displayed normally in this place again
![1705241250814](https://github.com/dromara/hertzbeat/assets/85116017/f285cf89-a0a1-410c-99b9-7368f41ca8a2)

and there is also a small bug here
![image](https://github.com/dromara/hertzbeat/assets/85116017/bf718441-a1e2-4d1b-b2b2-1f9a1fb16297)

This is my first time solving it, and I am trying to work hard to solve it

**Comment by GEM0816g** [comment]
> I encountered a problem in the front-end(前端) ![1705241174679](https://private-user-images.githubusercontent.com/85116017/296555023-de7c1e83-0203-48d8-b134-d500dd882cb6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDIxNjEsIm5iZiI6MTcwNTI0MTg2MSwicGF0aCI6Ii84NTExNjAxNy8yOTY1NTUwMjMtZGU3YzFlODMtMDIwMy00OGQ4LWIxMzQtZDUwMGRkODgyY2I2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YmYyNGNhMTFiOGM2ZDNlZjI4YTZmMjlmMmI4MzljNGQwNWE1MjIzNWQxOTVhMWUzYzBjMTM0ZWVhN2Q1OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zb3nubyyCscrZvOouMa2HTTkkj9opOtxENMJysX8Po0) I have added fields and displayed them, but it seems to be ineffective. I didn't seem to find the right place. May I ask where this was rendered (my front-end is very poor) And here ![1705241558550](https://private-user-images.githubusercontent.com/85116017/296555297-cc7bcbfa-a273-4526-a036-c550554a8a4e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDIxNjEsIm5iZiI6MTcwNTI0MTg2MSwicGF0aCI6Ii84NTExNjAxNy8yOTY1NTUyOTctY2M3YmNiZmEtYTI3My00NTI2LWEwMzYtYzU1MDU1NGE4YTRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYWNiYmVmM2I2MzU3ZDg0OTY0OTljNjUzMjFhMTY4YjIzMmE1OWQ2ZjY3MzZkMzE4ZTM4ZGMxNjE2YzUwN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGMV_llOTT-7t1puMN7WUz0ji-t23zluDVTAz6zbt6A)
> 
> But it can be displayed normally in this place again ![1705241250814](https://private-user-images.githubusercontent.com/85116017/296555353-f285cf89-a0a1-410c-99b9-7368f41ca8a2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDIxNjEsIm5iZiI6MTcwNTI0MTg2MSwicGF0aCI6Ii84NTExNjAxNy8yOTY1NTUzNTMtZjI4NWNmODktYTBhMS00MTBjLTk5YjktNzM2OGY0MWNhOGEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYmExOWRjNWUxZWU1ZTZhYTAxZjMxODczM2U3OTFmYWRkYmRmYjZiNDA5MGQ1ZTI1YjAwYzFiN2Y1OGViY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Skm4XrBh4IqNSkbvgQ8NREpK4UHh72UouEw90jfEY_c)
> 
> and there is also a small bug here ![image](https://private-user-images.githubusercontent.com/85116017/296555388-bf718441-a1e2-4d1b-b2b2-1f9a1fb16297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDIxNjEsIm5iZiI6MTcwNTI0MTg2MSwicGF0aCI6Ii84NTExNjAxNy8yOTY1NTUzODgtYmY3MTg0NDEtYTFlMi00ZDFiLWIyYjItMWY5YTFmYjE2Mjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NWU0MjVjOTI4ZjRkYjgwYzQyODBjN2Y2MTU0NGRjNzRhZDViOWM4Yjg2ZDVlM2RmODMwN2QyNmIwYWZlZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHtoyDKs2lM4E4fiS2GQRpLGTltPQjq8AUgTRCSXJ-I)
> 
> This is my first time solving it, and I am trying to work hard to solve it

@tomsun28

**Comment by GEM0816g** [comment]
I encountered a problem in the front-end(前端) ，I have added fields and displayed them, but it seems to be ineffective. I didn't seem to find the right place. May I ask where this was rendered (my front-end is very poor) 
![1705241174679](https://github.com/dromara/hertzbeat/assets/85116017/b0c1fc71-2235-4f90-a374-b4fbe9ad503d)
And here 
![1705241558550](https://github.com/dromara/hertzbeat/assets/85116017/f490cead-0139-4d25-8e2d-a012916e78eb)

But it can be displayed normally in this place again 
![1705241250814](https://github.com/dromara/hertzbeat/assets/85116017/6244329a-7507-4df1-af08-f467f1dc8b46)


and there is also a small bug here 
![1705242635250](https://github.com/dromara/hertzbeat/assets/85116017/944d1355-ef45-4a2d-9607-d52cee8566e1)


This is my first time solving it, and I am trying to work hard to solve it

@tomsun28

**Comment by tomsun28** [comment]
hi👍👍, we can consider dispaly the `description` field in `tag management page` only.  It is an additional description of the tag. If the user wants to know this `description`, he can go to the `tag management page` to view it.
