### ISSUE TITLE
[Task] <mongodb monitoring support custom connection timeout param>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1487]
### Description

mongodb monitoring support custom connection timeout param

### Task List

- [ ] mongodb monitoring support custom connection timeout param

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Can you provide more details about this issue

**Comment by tomsun28** [comment]
> Can you provide more details about this issue

hi, now we can monitoring mongodb by input ip, username, password and some params. But we can not custom config the connect timeout time when try connect to mongodb. Like this,

<img width="1285" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/42618f59-9eaf-43aa-a760-9f375145a417">

**Comment by ZY945** [comment]
> > Can you provide more details about this issue
> 
> hi, now we can monitoring mongodb by input ip, username, password and some params. But we can not custom config the connect timeout time when try connect to mongodb. Like this,
> 
> <img alt="image" width="1285" src="https://private-user-images.githubusercontent.com/24788200/315848414-42618f59-9eaf-43aa-a760-9f375145a417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzYwOTcsIm5iZiI6MTcxMTYzNTc5NywicGF0aCI6Ii8yNDc4ODIwMC8zMTU4NDg0MTQtNDI2MThmNTktOWVhZi00M2FhLWE3NjAtOWYzNzUxNDVhNDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE0MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMzFlNDZlNTU2Y2Q4ZDkwNjlmZDg4MDY5M2M0YjgzNTRiYjUzZGNmYWYzYjA2MDNkMTkwOTIzNmViYzgxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E06hYIbY2MlXJJyYVbKkwQE2tUjA3Blnp6Fs2-C_MyE">

We can try using MongoClientSettings
https://www.mongodb.com/zh-cn/docs/drivers/java/sync/current/fundamentals/connection/mongoclientsettings/
