### ISSUE TITLE
hertzbeat接入prometheus的告警接口**:**/metrics 告警问题

### ISSUE THREAD

**Issue by xingfeng7788** [dromara/hertzbeat#1495]
### Question

请问， hertzbeat接入prometheus的告警接口**:**/metrics 配置告警阈值，告警中心一直没有数据，请问怎么配置有没有问题
告警阈值配置
![image](https://github.com/dromara/hertzbeat/assets/25783998/3a03bb2f-6d63-4f1a-b544-10aeb8e0a7f2)
prometheus采集监控
![image](https://github.com/dromara/hertzbeat/assets/25783998/b8ffbd7a-3e55-421c-9721-c1c9c7998c96)

**Comment by tomsun28** [comment]
hi, 如果你没有开启阈值应用全局，那就应该在把阈值规则和监控关联起来。建议直接开启应用全局。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, if you have not enabled threshold application globally, you should associate threshold rules with monitoring. It is recommended to directly enable the application globally.

**Comment by xingfeng7788** [comment]
我之前是将阈值规则和监控关联起来了。刚刚我又试了下开启应用全局 也是没有效果，还有那个环节出现问题
![image](https://github.com/dromara/hertzbeat/assets/25783998/4360449d-1f31-43dd-a22b-87d9287a0a14)

**Comment by tomsun28** [comment]
收到🫡 我们后面复现下，也欢迎一起解决

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Received 🫡 We will reproduce it later, and you are welcome to solve it together.

**Comment by xingfeng7788** [comment]
ok thank you

**Comment by xingfeng7788** [comment]
@tomsun28 大佬麻烦重新打个镜像 我拉取了最新的镜像 发现补丁没搞进去，我本地运行了下代码是可以用的，应该是代码没有打进最新image

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@tomsun28 Sir, please re-image. I pulled the latest image and found that the patch was not installed. I ran the code locally and it worked. It should be that the code did not enter the latest image.

**Comment by tomsun28** [comment]
@xingfeng7788 你看看是不是因为本地的镜像没有删除，拉取远程镜像之后其实用的还是之前的老镜像

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@xingfeng7788 See if it’s because the local image has not been deleted. After pulling the remote image, the old image is still used.

**Comment by xingfeng7788** [comment]
已经是最新的镜像了 麻烦是确认下哈

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It is already the latest image. Please confirm it.

**Comment by tomsun28** [comment]
好的 收到

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Alright, I got it

**Comment by tomsun28** [comment]
hi, 我这边拉取最新镜像是生效的。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, the latest image I pulled here is effective.
