### ISSUE TITLE
[BUG] <Does monitorHost in the message notification template refer to the resource IP>

### ISSUE THREAD

**Issue by hiqumin** [dromara/hertzbeat#1508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在企业微信机器人的消息通知模版中想显示资源IP，配置monitorHost字段不生效。
![image](https://github.com/dromara/hertzbeat/assets/26481310/40b880ad-38ce-4822-8d88-55c967f9b686)

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
hi, we do not has the `monitorHost` variable default. We can consider support it after.

**Comment by UdayRajVadeghar** [comment]
i dont think there is any "monitorHost" variable.
