### ISSUE TITLE
hertzbeat自己监控自己，经常会出现误报警

### ISSUE THREAD

**Issue by daqianxiaoyao** [dromara/hertzbeat#151]
hertzbeat自己监控自己的时候，会出现误报警，我的是操作系统监控的时候 会出现误报警，只有重启hertbeat服务后，才能重新监控自己。如果不重启，就始终无法再监控自己

**Comment by tomsun28** [comment]
建议用 http 或 端口 对自己服务监控 或者 版本升级至[v1.0](https://github.com/dromara/hertzbeat/releases/tag/v1.0)后观察是否linux ssh监控自己是否还会误报

**Comment by tomsun28** [comment]
Hi 还会出现此问题吗，或者您用端口检测 网站监测来监控Hertzbeat。我先把此issue关闭了。
