### ISSUE TITLE
经常出现hertzbeat服务假死，浏览器无法访问hertzbeat

### ISSUE THREAD

**Issue by daqianxiaoyao** [dromara/hertzbeat#152]
hertzbeat一开始可以正常使用，但是会突入出现hertzbeat假死的情况，就是：在浏览器上无法再访问hertzbeat。这时候去查看资源占用，会发现CPU基本跑满，内存基本耗关。重启hertzbeat后，又恢复正常，可以正常访问hertzbeat

**Comment by tomsun28** [comment]
hi thanks for issue,  this problem will be fix by #153

**Comment by tomsun28** [comment]
hi, the version [hertzbeat v1.0](https://github.com/dromara/hertzbeat/releases/tag/v1.0) fix it
