### ISSUE TITLE
[Task] <support http_sd_config protocol to auto monitoring instance>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1526]
### Description

support http sd protocol to auto monitoring instance

refer: 

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config

https://prometheus.io/docs/prometheus/latest/http_sd/

https://gitee.com/dromara/RuoYi-Cloud-Plus/blob/2.X/ruoyi-visual/ruoyi-monitor/src/main/java/org/dromara/modules/monitor/controller/PrometheusController.java

### Task List

- [ ] support http sd protocol to auto monitoring instance
- [ ] relate use document

**Comment by Calvin979** [comment]
I'd like to help!

**Comment by Calvin979** [comment]
#1618

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
#1618
