### ISSUE TITLE
组织：TanCloud https://tancloud.cn

### ISSUE THREAD

**Issue by luwei370** [dromara/hertzbeat#1539]
组织：syt公司
地点：长沙，中国
联系方式： 642108730@qq.com
使用场景：网站监控，服务器监控，服务端口可用性监控 告警通知
使用感受：简单易用，小白用windows server部署很快，中间在告警阀值设置那里卡了很久，加了大神微信后一下就解决了，是我想得太复杂了，哈哈

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Organization: syt company
Location: Changsha, China
Contact information: 642108730@qq.com
Usage scenarios: website monitoring, server monitoring, service port availability monitoring, alarm notification
Usage experience: Simple and easy to use. Newbies can deploy quickly using windows server. I was stuck for a long time in setting the alarm threshold. After adding the master WeChat, it was solved immediately. I thought it was too complicated, haha@@== ==Organization: TanCloud https://tancloud.cn
