### ISSUE TITLE
[Question] Can the enterprise WeChat alarm service address be Migrate to profile?

### ISSUE THREAD

**Issue by QuarkSunJM** [dromara/hertzbeat#1547]
### Question

将hertzbeat部署到内网中，如果需要使用企业微信服务进行消息提醒，我们必需要通过代理才能访问到外网。
而当前版本中的企业微信通信地址是写死在代码中的，建议后续版本中将此内容迁移到配置文件中(application.yml)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question


Deploy hertzbeat to the intranet. If we need to use the enterprise WeChat service for message reminders, we must use a proxy to access the external network.
The enterprise WeChat communication address in the current version is hard-coded in the code. It is recommended that this content be migrated to the configuration file (application.yml) in subsequent versions.

**Comment by zqr10159** [comment]
最新的1.5.0版本 yml配置文件已经可以配置地址
![image](https://github.com/dromara/hertzbeat/assets/30048352/829c7c93-0529-4453-bdf0-61be7af4168c)

**Comment by zqr10159** [comment]
#1535

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
#1535
