### ISSUE TITLE
Add gotify notification support

### ISSUE THREAD

**Issue by Omoinemie** [dromara/hertzbeat#1552]
### Question

目前功能里面没有gotify通知模板，希望支持一下，谢谢！

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

There is currently no gotify notification template in the function. I hope you can support it. Thank you!

**Comment by zqr10159** [comment]
好的，我来看一下，争取下版本就上线

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Okay, let me take a look and try to launch it in the next version.

**Comment by zqr10159** [comment]
![image](https://github.com/dromara/hertzbeat/assets/30048352/33c351f7-f1bb-473b-ba38-ba9bb47c93b4)
@Omoinemie 这样是否可以，可以我合并进master你编译就可以先用着了

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![image](https://github.com/dromara/hertzbeat/assets/30048352/33c351f7-f1bb-473b-ba38-ba9bb47c93b4)
@Omoinemie Is this possible? I can merge it into master and you can compile it and use it first.

**Comment by Omoinemie** [comment]
很好了，谢谢

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Very good, thank you

**Comment by zqr10159** [comment]
![image](https://github.com/dromara/hertzbeat/assets/30048352/d258b564-8add-467a-becf-17c5862ee1b5)
顺便说一下，你需要在yml里配置你的gotify server地址
