### ISSUE TITLE
[Task] <fix and pass the checkstyle error in `alerter` module code>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1576]
### Description

fix and pass the checkstyle error in `alerter` module code  
module https://github.com/dromara/hertzbeat/tree/master/alerter 

 run `mvn compile` in `alerter` module, you will see the style error, fix it and pass the checkstyle

<img width="1123" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/42f3dd74-eadb-424b-a497-b9f97f25f30d">

**Comment by ZY945** [comment]
I want to help。
