### ISSUE TITLE
[Task] <fix and pass the checkstyle error in `collector` module code>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1577]
### Description

fix and pass the checkstyle error in `collector` module code  
module https://github.com/dromara/hertzbeat/tree/master/collector 

 run `mvn compile` in `collector` module, you will see the style error, fix it and pass the checkstyle

<img width="961" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/369fb8e0-08c0-4e1f-984f-f8eda9cff13b">

**Comment by TJxiaobao** [comment]
I want to help。
