### ISSUE TITLE
[Task] <fix and pass the checkstyle error in `common` module code>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1578]
### Description

fix and pass the checkstyle error in `common` module code  
module https://github.com/dromara/hertzbeat/tree/master/common 

run `mvn compile` in `common` module, you will see the style error, fix it and pass the checkstyle

<img width="957" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/6dcca3dd-e465-4bcd-91af-56ab7975ca5d">

**Comment by a-little-fool** [comment]
I want to help
