### ISSUE TITLE
[Task] <fix and pass the checkstyle error in `warehouse` module code>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1580]
### Description

fix and pass the checkstyle error in `warehouse` module code  
module https://github.com/dromara/hertzbeat/tree/master/warehouse 

 run `mvn compile` in `warehouse` module, you will see the style error, fix it and pass the checkstyle

<img width="794" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/4639e793-faf2-4395-9ac5-d36cfeea03ab">

**Comment by zqr10159** [comment]
I want to help
