### ISSUE TITLE
[Task] <support config ui theme in System Configuration>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1597]
### Description

support config ui theme in System Configuration, remove the theme-button

<img width="1132" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/35f41cdd-184d-48d5-82f4-137aba1c5bff">

remove the theme button here.

<img width="1455" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/e4d2ed97-1b7b-407f-b0ce-574799790f2a">

**Comment by forcejie** [comment]
I want to help

**Comment by Mafifa** [comment]
Still available?

**Comment by tomsun28** [comment]
@forcejie welcome, has assgined to you.

**Comment by tomsun28** [comment]
@forcejie hi, the config button has done here https://github.com/dromara/hertzbeat/pull/1636 
And we need to trigger the actual switching of the page color theme after choosing to switch the theme. Can you help us to work with @TJxiaobao to solve it?   

https://github.com/dromara/hertzbeat/pull/1636
