### ISSUE TITLE
[BUG] <title> There is a problem with the latest master code monitoring mongodb

### ISSUE THREAD

**Issue by TJxiaobao** [dromara/hertzbeat#1664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the latest master code to deploy locally to monitor mongodb has a problem that makes it impossible to monitor.
![image](https://github.com/dromara/hertzbeat/assets/85919258/8a7f5d59-4601-469d-8eff-dd18c029ee3c)

The possible reason is that the latest version is upgraded to SpringBoot3, which may cause dependency issues.

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
discuss with @ZY945, This should be because the original springboot2 included the mongodb core dependency. After we upgraded to springboot3, this dependency was not built in, causing problems. In theory, adding missing dependencies can solve the problem.
