### ISSUE TITLE
[Task] <update logback config>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1704]
### Description

update logback config, smaller the `totalSizeCap` and `maxFileSize`, do not print log in console when in prod envrionment. 

### Task List

- [ ] update manager and collector logback config.

**Comment by handy-git** [comment]
<totalSizeCap>5GB</totalSizeCap> 
<maxFileSize>50MB</maxFileSize> 

是否可行，讨论下

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
 

<totalSizeCap>5GB</totalSizeCap> 
<maxFileSize>50MB</maxFileSize> 

Let’s discuss if it’s feasible

**Comment by tomsun28** [comment]
OK👍
