### ISSUE TITLE
[BUG] Linux host monitoring cannot view history <title>

### ISSUE THREAD

**Issue by StellaBird** [dromara/hertzbeat#1715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![hbeat_issue01](https://github.com/dromara/hertzbeat/assets/89234191/d095b3ad-f14d-4310-b766-c9fc82bc6854)
如截图所示，linux主机监控历史图表无法正常显示
使用版本：HertzBeat v1.5.0

### Steps To Reproduce

Docker Compose 部署

### Environment

```markdown
HertzBeat version(s):v1.5.0
```

**Comment by tomsun28** [comment]
Did you use an external time series database?

**Comment by StellaBird** [comment]
> Did you use an external time series database?

应该是时序数据库的问题，使用的是docker compose 内置的，但对应conf 目录下的2个yml文件已经很久没有更新过了，现在重新修改调整了一下，观察后再反馈

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Did you use an external time series database?

It should be a problem with the time series database. We use the built-in docker compose, but the two yml files corresponding to the conf directory have not been updated for a long time. Now we have revised and adjusted them, and we will give feedback after observation.

**Comment by StellaBird** [comment]
最新反馈：之前采用的是docker compose(hertzbeat-mysql-iotdb)方式部署，升级至1.5.x版本后发现时序数据库异常，现采用(hertzbeat-mysql-victoria-metrics)方法部署，历史采集数据显示正常。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Latest feedback: Previously, the docker compose (hertzbeat-mysql-iotdb) method was used for deployment. After upgrading to version 1.5.x, an abnormality was found in the time series database. Now the (hertzbeat-mysql-victoria-metrics) method is used for deployment, and the historical collection data is displayed normally. .

**Comment by tomsun28** [comment]
因为版本历史和规划，我们推荐使用 victoria-metrics

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Because of version history and planning, we recommend using victoria-metrics
