### ISSUE TITLE
[BUG]  16/10000 实时翻译 划译 Historical data insertion into tdengine failed

### ISSUE THREAD

**Issue by weixiaochun1998** [dromara/hertzbeat#1720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

【版本】 1.3.2
【环境】 使用tdengine存储历史数据
【问题】 当自定义监控的名称首字母为大写时，生成的创建超级表语句会增加 `` 符号，但是插入的时候，指定超级表时没有 `` 符号，会一直导致插入失败，具体如图：
![image](https://github.com/dromara/hertzbeat/assets/108884213/5d49b51c-e0d8-4286-91e0-53c80b4bd4f2)
![image](https://github.com/dromara/hertzbeat/assets/108884213/b162704f-a25a-47cb-b9b1-eeaa19a89f98)
![image](https://github.com/dromara/hertzbeat/assets/108884213/1a10a649-f2b7-4387-9038-50a23244b276)

### Expected Behavior

在适当的地方增加说明，或修改生成的DDL语句

### Environment

```markdown
HertzBeat version(s):
```

**Comment by weixiaochun1998** [comment]
Tdengine版本：3.0.4.0

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Tdengine version: 3.0.4.0

**Comment by zqr10159** [comment]
Please update hertzbeat to the latest version 1.5.0, the latest version does not have this problem!

**Comment by zqr10159** [comment]
Please update hertzbeat to the latest version 1.5.0, the latest version does not have this problem!
