### ISSUE TITLE
[Task] support MongoDB database monitor

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#177]
**Describe the solution you'd like**. 

support MongoDB metrics monitor

**Additional context**

https://www.mongodb.com/

**Comment by liudonghua123** [comment]
I would expect this features too.

**Comment by tomsun28** [comment]
welcome to contribute this feature. @liudonghua123

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
welcome to contribute this feature. @liudonghua123

**Comment by liudonghua123** [comment]
I tried to write an initial mongodb support, and tested ok on my own mongodb server.

Please review and merge the code, thanks!

**Comment by tomsun28** [comment]
This pr is great! thanks for contribution. 👍
