### ISSUE TITLE
[Task] support ClickHouse database monitor

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#179]
**Describe the solution you'd like**. 

support ClickHouse database monitor. 

**Additional context**

https://clickhouse.com/

**Comment by tomsun28** [comment]
metrics https://clickhouse.com/docs/zh/operations/monitoring/ we can use http /ping to monitor it's health

https://clickhouse.com/docs/zh/operations/system-tables/metrics/#system_tables-metrics 

https://clickhouse.com/docs/zh/operations/system-tables/events/#system_tables-events 

https://clickhouse.com/docs/zh/operations/system-tables/asynchronous_metrics/#system_tables-asynchronous_metrics

**Comment by orangeyts** [comment]
Got it
