### ISSUE TITLE
标签扩展

### ISSUE THREAD

**Issue by Suremotoo** [dromara/hertzbeat#18]
下载本地体验了一下，还是挺不错的～本人很喜欢 👍

macOS 貌似使用 docker 算是比较好的方案， 除了 **TDengine** 我都在本地运行～
**TDengine** 不用 docker ，说实话，我在本地 macOS 环境貌似无法运行。
最终我把 TDengine 搭建在了我的私人服务器上，才得以完美运行。

建议：
关于监控维护列表里，能增加标签类的设置和过滤功能嘛？有时候一台服务器往往会部署多台应用什么的，不同的应用不同的端口～ 🥺

当然了，也能增加上其他一些查询过滤条件，比如 监控 Host、监控名称、端口 这样的条件～

**Comment by tomsun28** [comment]
哈哈 给这么详细的体验描述点赞，tdengine我本地可以docker起来，谢谢监控列表那块的建议，后面把查询过滤条件功能加上，tag的这个建议可以有，我在其它系统也看到过。👍👍

**Comment by Suremotoo** [comment]
这两天又进一步用了用，深切喜欢这个软件 🥰🥰～

> 哦对了，前面提到的 **tdengine** 是说我本地 macOS 没有用 docker 的情景下，没能跑起来，最终还是在我私人 linux 服务器上跑的 **tdengine**（可能我不懂这个 **tdengine**），怪我前面没有描述清楚～😅😅，不过这个不重要了～

> 我的搭建环境，除了 **tdengine** 没在本地，其余都在本地

另一个不好意思的地方，是过滤条件我发现咱其实也有，只是在最上方，之前没注意到
<img width="448" alt="CleanShot 2022-03-14 at 16 13 35@2x" src="https://user-images.githubusercontent.com/26423989/158131362-674333a6-69cb-4579-83ca-383f9ccdafcb.png">

不过，我觉得该功能还是可以再优化的，详情见下属建议第 1 点。

--------

但是根据我个人的使用，我又想提出几点建议，也希望作者能考虑考虑 🤞。

1. 页面全局监控搜索：比如我的资源名称：**TELNET_10.10.10.100_随便节点服务器_8088** ，我搜索中文“**随便**”等，可能没有结果，搜索“**8088**” 也没有结果 😔

2. 列表种时间展示问题，最好标准成： **yyyy-MM-dd HH:mm:ss** 这样的格式（年月日 时分秒，24 小时制），当前的展示确实不利于查看，诺：
   <img width="205" alt="CleanShot 2022-03-14 at 16 18 53@2x" src="https://user-images.githubusercontent.com/26423989/158132249-52b873ca-daf5-448c-be30-526f51e2982f.png">

3. 数据库监控，总会超时，探测都是 OK 的
 这个情景是由于我使用了公司的 VPN，本地直接连接公司数据库都是走 VPN 的，当然我本地通过数据库可视化工具连接什么的都没问题，这个应该是我这边的问题，不过这个超时时间，如果长点会不会解决我这个情景的问题呢？ 🤔

**Comment by tomsun28** [comment]
哈哈感谢🙏这些建议，很开心能得到这样的评价。 

1. 页面全局监控搜索：比如我的资源名称：TELNET_10.10.10.100_随便节点服务器_8088 ，我搜索中文“随便”等，可能没有结果，搜索“8088” 也没有结果 😔

> 这个看样子是个BUG 我后面修复下。     

2. 列表种时间展示问题，最好标准成： yyyy-MM-dd HH:mm:ss 这样的格式（年月日 时分秒，24 小时制），当前的展示确实不利于查看 

> get 这个要改下 现在是直接用的UTC时间 不便于查看。

4. 数据库监控，总会超时，探测都是 OK 的.      

> 这个我去复现下看是不是BUG或者其它配置原因。 目前time-out是写死的，那我下一版本把timeout暴露出来让可配置

**Comment by wang1027-wqh** [comment]
我觉得如果是vpn链接的话 这种的我们可以提供一个范围值，做成一个可接受的ping值范围

**Comment by tomsun28** [comment]
support #111  next version v1.0.beat.8

**Comment by tomsun28** [comment]
hi tags manage support with v1.0-beat.8 https://github.com/dromara/hertzbeat/releases/tag/v1.0-beta.8
