### ISSUE TITLE
是否支持监控搭设在境外的云服务器【new feature】

### ISSUE THREAD

**Issue by 564398053** [dromara/hertzbeat#2]
中小企业的互联网出海的项目通常搭设在amozon等云服务器上，是否 `https://console.tancloud.cn/` 有考虑支持。

**Comment by tomsun28** [comment]
hi 后期云环境TanCloud会考虑在海外部署采集器供海外监控

**Comment by 564398053** [comment]
来信已收到，谢谢

**Comment by yinzixie** [comment]
在海外访问你们的网站也太慢了。。。

**Comment by 564398053** [comment]
来信已收到，谢谢

**Comment by tomsun28** [comment]
> 在海外访问你们的网站也太慢了。。。

@yinzixie 目前都部署在国外节点
@564398053 (^-^)
