### ISSUE TITLE
docker部署后，告警通知到企业微信，内容详情 提示的是英文

### ISSUE THREAD

**Issue by liangkangning** [dromara/hertzbeat#214]
[HertzBeat告警通知]
告警目标对象 : available
所属监控ID : 9093852115763200
所属监控名称 : docker-xxx
告警级别 : 警告告警
告警触发时间 : 2022-07-07 15:31:02
内容详情 : Availability Alert Resolved, Monitor Status Normal Now

部署的命令如下：
docker run -d -p 1157:1157 --name hertzbeat tancloud/hertzbeat  

容器的环境变量如下：
`
/opt/hertzbeat # env
JAVA_ALPINE_VERSION=8.212.04-r0
HOSTNAME=633a10ef674b
SHLVL=1
HOME=/root
JAVA_VERSION=8u212
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
LANG=C.UTF-8
JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
PWD=/opt/hertzbeat
TZ=Asia/Shanghai`
`

**Comment by tomsun28** [comment]
hi 在docker启动时设置环境语言可以把内容变更为中文 
```
docker run -d -p 1157:1157 -e LANG=zh_CN.UTF-8 --name hertzbeat tancloud/hertzbeat

```

**Comment by hzl7652** [comment]
使用 docker-compose 部署最新版本还是出现告警全是英文问题

[HertzBeat Alert Notify]
Monitor Target :available
Monitor ID :146729323161856
Monitor Name :WEBSITE_152.136.135.236
Alert Priority :Warning Alert
Alert Trigger Time : 2022-07-20 15:56:44
Alert Content : Availability Alert Resolved, Monitor Status Normal NowConsole Login

**Comment by tomsun28** [comment]
@hzl7652 谢谢反馈 收到

**Comment by tomsun28** [comment]
@hzl7652 hi 使用最新的 v1.1.2 版本 fix
