### ISSUE TITLE
网站监测 响应时间历史图表没显示出来

### ISSUE THREAD

**Issue by 57321** [dromara/hertzbeat#227]
**Describe the bug**

2022-07-21 09:44:11.921 [http-nio-1157-exec-8] WARN  com.usthe.warehouse.store.TdEngineDataStorage Line:282 - TDengine ERROR (200): sql: SELECT ts, instance, responseTime FROM website_summary_146396384667904 WHERE ts >= now - 6h order by ts desc, desc: invalid operation: invalid column name

![image](https://user-images.githubusercontent.com/38900476/180111896-d2c1b86f-22ec-4340-a61a-0fd13e325609.png)

![image](https://user-images.githubusercontent.com/38900476/180111912-01e1db48-1e17-4886-aae2-13de790bc337.png)

**Used Version**  
最新版本 v1.1.1

从描述看 少了个desc字段。

**Comment by tomsun28** [comment]
website 监控类型下的 `desc` 指标是您自定义的后加入的么? 需要修改tdengine超级表添加这个字段或者删除超级表等待自动重建

**Comment by 57321** [comment]
我没弄过自定义监控
删了还是不行
![image](https://user-images.githubusercontent.com/38900476/180179406-41e663fc-d1f8-4efa-9ecf-7493088b5984.png)
![image](https://user-images.githubusercontent.com/38900476/180179702-bcecff39-358a-4d08-92bd-eb60c26760ae.png)
翻了下源码 确实有这个desc 但是超级表没这个字段
![image](https://user-images.githubusercontent.com/38900476/180182814-05ddffc2-2c6a-417e-96a5-ca544eee404d.png)

**Comment by 57321** [comment]
不好意思，搞晕了 desc 是倒序 
我试了这条SQL 应该是 responseTime 这个字段不行
![image](https://user-images.githubusercontent.com/38900476/180184900-b11c2996-ff1a-4858-bc7f-479280caac74.png)

**Comment by tomsun28** [comment]
hi 不好意思之前没上线 有可能 我后面本地复现下奥

**Comment by tomsun28** [comment]
@57321 hi 定位是tdengine版本的问题 我们使用您说的 2.6.0.6 版本会复现此问题，使用 2.4.0.4 无此问题，建议更换tdengine版本
