### ISSUE TITLE
应用服务器监控  HTTP API 关键字提取不成功

### ISSUE THREAD

**Issue by BigWatermelonOne** [dromara/hertzbeat#236]
获取es jvm 关键字，请求成功未提取成功
![image](https://user-images.githubusercontent.com/110441390/182286315-7284ad51-f524-4d78-a28a-2566bc256e44.png)
![image](https://user-images.githubusercontent.com/110441390/182286340-c816c14d-dc9c-4ed5-81d5-67fd040dcae4.png)
![image](https://user-images.githubusercontent.com/110441390/182286485-f8d0ec96-4def-4daa-8acd-c7e183a80d10.png)

**Comment by tomsun28** [comment]
jsonpath是在自定义监控时配置yml定义脚本的，这里的关键字的意思是 匹配返回的内容中有多少个关键词 比如 jvm 这个就应该有1个。 
我看您想要实现的应该是采集指标 heap_used_precent 的值 这个可以通过http自定义监控配置jsonpath来实现
