### ISSUE TITLE
Historical Chart has no metrics data with tdengine 2.6.0.14

### ISSUE THREAD

**Issue by EricFROL** [dromara/hertzbeat#254]
**Describe the bug**
"Monitor Historical Chart Detail" returns No metric data.

**Used Version**  
Docker v1.1.2.

**To Reproduce**
1. Setup Mysql in a external machine, and get it working.
2. Setup TDEngine in a extenal machine, and get it working.
3. Setup Hertzbeat as a docker container, and check if it writes into databases: it does.
4. Service monitor -> Ping 192.168.1.1 -> Monitor Historical Chart Detail 
5. Error

**Expected behavior**
Be able to see graphs.

**Screenshots**
![Captura](https://user-images.githubusercontent.com/42719382/185790835-80df72f0-cf02-477f-a7b3-4b6c624cd787.JPG)

This was the service I was looking for, it's perfect. What a shame I can not get it working :(

**Comment by tomsun28** [comment]
Hi, Do the Real-Time Detail has data?  I guess because you set the monitor interval is 600s,  you need to wait a little longer to check.  

Or you can turn it down a bit and have a try. 

<img width="839" alt="2022-08-21 21 10 59" src="https://user-images.githubusercontent.com/24788200/185792530-cea60ddd-5b5c-4c4b-a955-90db0ddfe9cb.png">

**Comment by EricFROL** [comment]
You mean this? 
![Captura](https://user-images.githubusercontent.com/42719382/185792747-41a8fe9a-3d28-4d0d-8f8e-abc1592905d2.JPG)

![Uploading Captura.JPG…]()

**Comment by tomsun28** [comment]
Yes

**Comment by EricFROL** [comment]
Still without data...

**Comment by tomsun28** [comment]
so sad.
Can you get the log in hertzbeat docker container?

```
docker exec -it hertzbeat sh
```
watch the logs in /opt/hertzbeat/logs/ 

By the way, what is the hertzbeat version and tdengine version? Do the Real-Time Detail has data?

**Comment by EricFROL** [comment]
I noticed that when I request a query of "x" time, logs return:
`2022-08-21 23:31:50.734 [http-nio-1157-exec-6] WARN  com.usthe.warehouse.store.TdEngineDataStorage Line:299 - TDengine ERROR (200): sql: SELECT ts, instance, responseTime FROM ping_summary_157834084603136 WHERE ts >= now - 6h order by ts desc, desc: invalid operation: invalid column name`

![Captura](https://user-images.githubusercontent.com/42719382/185798880-49e592d4-6da7-4768-9190-14d987b65ae6.JPG)

HertzBeat v1.1.2
TDEngine 2.6.0.14

**Comment by tomsun28** [comment]
hi, this is cause by tdengine bug #227 
please try the tdengine version 2.4.0.4

**Comment by EricFROL** [comment]
'Aight man, got it working. TY so much.

Btw, this bug must be solved, in order to continue using last verison of TDEngine.

**Comment by EricFROL** [comment]
One more thing, how can I check graphs older than 1 month?

**Comment by tomsun28** [comment]
Sorry for the late reply, I went to bed last night. 

> One more thing, how can I check graphs older than 1 month?

The current limit is one month, you can feedback a feature issue, we will implement it in the next version.

**Comment by EricFROL** [comment]
'Aight, I'm gonna do that.
Thank you tomsun28.
