### ISSUE TITLE
Charts with custom time range.

### ISSUE THREAD

**Issue by EricFROL** [dromara/hertzbeat#256]
**Describe the solution you'd like**
Be able to look graphs older than one month; as title says, charts with custom time range.
This would be perfect.

**Comment by tomsun28** [comment]
hi thanks for suggest. It has be supported in version v1.1.3.  
We provide historical data for the last three months, then you can select them with the range selector.

<img width="627" alt="2022-09-04 18 22 31" src="https://user-images.githubusercontent.com/24788200/188308730-cd79f350-8501-4424-adc6-7c1d776d3bdd.png">

**Comment by EricFROL** [comment]
> hi thanks for suggest. It has be supported in version v1.1.3.  
> 
> We provide historical data for the last three months, then you can select them with the range selector.
> 
> 
> 
> <img width="627" alt="2022-09-04 18 22 31" src="https://user-images.githubusercontent.com/24788200/188308730-cd79f350-8501-4424-adc6-7c1d776d3bdd.png">
> 
> 

Nice, where is that "range selector"?

**Comment by tomsun28** [comment]
The Zoom In, Zoon Out.
