### ISSUE TITLE
[Task] Sort "Monitor" hosts by name, added date, etc.

### ISSUE THREAD

**Issue by EricFROL** [dromara/hertzbeat#259]
**Is your feature request related to a problem? Please describe.**
I plan to add all my LAN devices into hertzbeat as "PING CONNECT" monitoring. So it would be nice to be able to sort that large amount of hosts by name, instead of the current one: "added date".

**Describe the solution you'd like**
Be able to sort hosts by name.

**Comment by luxx-lq** [comment]
I would like to try

**Comment by tomsun28** [comment]
hi supported in version v1.2.2 now! https://github.com/dromara/hertzbeat/discussions/467. @luxx-lq thanks for contributing!
