### ISSUE TITLE
[BUG] <用户设置盐配置用户>无法登录(密码正常，盐正常读取)

### ISSUE THREAD

**Issue by QYG2297248353** [dromara/hertzbeat#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

用户设置自定义盐值，使用全大写UUID,登录报错
# 盐配置
![image](https://user-images.githubusercontent.com/56836951/189649650-2cbed8f4-bff1-41b8-9d51-caf3a62a0129.png)

# 盐加密结结果
![image](https://user-images.githubusercontent.com/56836951/189650117-1a1b1638-d2e1-47d0-895e-cb1058a9c186.png)

# 登录数据
![image](https://user-images.githubusercontent.com/56836951/189649904-a29e50b4-2f49-4725-acd0-2dc8dc4991e1.png)

# 异常原因 大小写异常
![image](https://user-images.githubusercontent.com/56836951/189650657-9a296243-3a71-4483-8bc2-2b4f57bbd025.png)

### Expected Behavior

无法正常登录

### Steps To Reproduce

配置UUID盐-全大写无连字符
配置加密密码

### Environment

```markdown
HertzBeat version(s):
```

### Debug logs

无

### Anything else?

无

**Comment by tomsun28** [comment]
收到 🫡 谢谢反馈 👍👍👍

**Comment by tomsun28** [comment]
Hi @QYG2297248353  这个是关联项目 sureness https://github.com/dromara/sureness 的 bug, 有兴趣对sureness提交代码修复下吗

**Comment by tomsun28** [comment]
fix by pr https://github.com/dromara/hertzbeat/issues/288
