### ISSUE TITLE
spring.mail改为非必填，优化部分告警阈值的返回处理

### ISSUE THREAD

**Issue by Ceilzcx** [dromara/hertzbeat#301]
### Description
spring.mail目前为必填，改为选配（不使用邮箱告警通知的功能可以去掉spring.mail相关配置）
优化部分告警阈值的返回处理，例：未配置或者错误配置mail的使用邮箱在告警通知发送告警测试时，仍会返回“触发告警测试成功!”（其他告警通知也有类似问题）
### Task List
- [x] - application.yml的spring.mail修改为选配
- [x] - 优化部分告警阈值的返回处理
_No response_

**Comment by tomsun28** [comment]
👍 support at v1.2.0
