### ISSUE TITLE
希望 阈值触发表达式 能够支持跨指标的自定义组合配置

### ISSUE THREAD

**Issue by colo1994** [dromara/hertzbeat#33]
比如CPU使用率大于80%且内存大于70%时候进行告警。

**Comment by tomsun28** [comment]
hi 这个需要考虑下   
目前支持指标集合下的所有指标自定义组合告警  比如Linux的memory内存下面的 total-总内存 free-空闲内存 `total>432432&&free>=234343` 这种阈值表达式配置。
但是不支持跨指标集合的阈值表达式组合，比如cpu指标集合下面的指标和memory下面的指标。  
这种跨集合的指标目前没找到好的计算关联方式，因为它们不是同一时刻采集的。
