### ISSUE TITLE
[BUG] <无跨域配置>

### ISSUE THREAD

**Issue by k4n5ha0** [dromara/hertzbeat#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/22064977/194744576-44f6b66a-842a-4447-8b8a-69c932ba5393.png)

### Expected Behavior

后台应能配置cors白名单

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
收到🫡

**Comment by tomsun28** [comment]
done, fix by PR #338
