### ISSUE TITLE
[Task] <Unit Test Case> manager/controller/AppControllerTest.java

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#348]
### Description

Help us impl Unit Test For [manager/src/test/java/com/usthe/manager/controller/AppControllerTest.java 
](https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AppControllerTest.java)   
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ] Impl Unit Test For [manager/src/test/java/com/usthe/manager/controller/AppControllerTest.java 
](https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AppControllerTest.java)

**Comment by TJxiaobao** [comment]
尝试认领一下这个任务嘿嘿

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Try claiming this quest hehe
