### ISSUE TITLE
[Task] <Unit Test Case> manager/controller/I18nControllerTest.java

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#349]
### Description

Help us impl unit test For [manager/controller/I18nControllerTest.java](https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/I18nControllerTest.java).   
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ] Impl Unit Test For [manager/controller/I18nControllerTest.java](https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/I18nControllerTest.java).

**Comment by TJxiaobao** [comment]
Let me have a try

**Comment by tomsun28** [comment]
👍 has published at version v1.2.1
