### ISSUE TITLE
[Task] <Unit Test Case> manager/service/MonitorServiceTest.java

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#357]
### Description

Help us impl Unit Test For [manager/service/MonitorServiceTest.java](https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/MonitorServiceTest.java)  
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ] Impl Unit Test For [manager/service/MonitorServiceTest.java](https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/MonitorServiceTest.java)

**Comment by orangeyts** [comment]
got it
