### ISSUE TITLE
[BUG] hertzbeat has a problem bypassing permissions

### ISSUE THREAD

**Issue by 2xiaodi** [dromara/hertzbeat#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

开发者您好，我很热爱这个开源项目，在使用中发现一点问题，关于hertzbeat系统的权限控制存在一定的安全隐患

### Steps To Reproduce

Normally, there is no Authorization request

![image](https://user-images.githubusercontent.com/57615079/197159313-ac0070eb-1708-4383-a857-f0df9e6af0dd.png)

The circumvention caused by a particular means

![image](https://user-images.githubusercontent.com/57615079/197157802-73039162-b12a-42f2-a185-5e8617eb99cf.png)

### Environment

```markdown
HertzBeat version(s):1.2.0
```

**Comment by tomsun28** [comment]
👍👍 thanks for feedback. this will be fixed by https://github.com/dromara/hertzbeat/pull/382

**Comment by tomsun28** [comment]
fixed at version v1.2.1
