### ISSUE TITLE
希望httpapi监控支持返回值校验

### ISSUE THREAD

**Issue by ikewang** [dromara/hertzbeat#39]
返回值校验支持比如包含、响应状态码等简单校验，在接口监控中非常重要。

**Comment by tomsun28** [comment]
收到谢谢建议，已加入roadmap后续支持。

**Comment by tomsun28** [comment]
hi 已支持 会在下个版本 1.0.beta.7发布 PR见 #72

**Comment by tomsun28** [comment]
hi it support now see 1.0.beta.7

**Comment by gcdd1993** [comment]
@tomsun28 你好，我部署了新版本1.0beta.7 ，但是HTTP API里面没有statusCode的监控指标。
![image](https://user-images.githubusercontent.com/26523525/163322362-03581bbb-2f2a-4382-927a-5b0d4a1d625f.png)

**Comment by tomsun28** [comment]
statusCode 在API调用时已判断 4XX 5XX为失败会直接发不可用告警
