### ISSUE TITLE
[Task] <Unit Test Case> com/usthe/warehouse/controller/MetricsDataControllerTest.java

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#406]
### Description

Help us impl Unit Test For [com/usthe/warehouse/controller/MetricsDataControllerTest.java](https://github.com/dromara/hertzbeat/blob/master/warehouse/src/test/java/com/usthe/warehouse/controller/MetricsDataControllerTest.java)     
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ]  Impl Unit Test For  [com/usthe/warehouse/controller/MetricsDataControllerTest.java](https://github.com/dromara/hertzbeat/blob/master/warehouse/src/test/java/com/usthe/warehouse/controller/MetricsDataControllerTest.java)

**Comment by haibo-duan** [comment]
pls assign it to me.
