### ISSUE TITLE
[Task] <Unit Test Case> com/usthe/warehouse/WarehouseWorkerPoolTest.java

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#407]
### Description

Help us impl Unit Test For [com/usthe/warehouse/WarehouseWorkerPoolTest.java](https://github.com/dromara/hertzbeat/blob/master/warehouse/src/test/java/com/usthe/warehouse/WarehouseWorkerPoolTest.java)     
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ]  Impl Unit Test For [com/usthe/warehouse/WarehouseWorkerPoolTest.java](https://github.com/dromara/hertzbeat/blob/master/warehouse/src/test/java/com/usthe/warehouse/WarehouseWorkerPoolTest.java)

**Comment by HattoriHenzo** [comment]
@tomsun28 Hi, assigne it to me.

**Comment by HattoriHenzo** [comment]
@tomsun28 I was to this task but it seems like a test has already been provided for this class. I have made a little refactoring on the class.
