### ISSUE TITLE
There are problems in collecting cpu cores and interrupts under Oracle Linux based on arm architecture

### ISSUE THREAD

**Issue by assassinfym** [dromara/hertzbeat#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Under the Oracle Linux based on the arm architecture, there is a problem in collecting cpu cores and interrupt, and it will display&nbsp
![image](https://user-images.githubusercontent.com/15188754/200468908-795eb151-2434-475d-a235-9771cc92082a.png)

After analyzing the source code, it is found that it is a script for collecting cpu, and there are some compatibility problems

Original collection script

LANG=C lscpu | awk -F: '/Model name/ {print $2}';awk '/processor/{core++} END{print core}' /proc/cpuinfo;uptime | sed 's/,/ /g' | awk '{for(i=NF-2;i<=NF;i++)print $i }' | xargs;vmstat 1 1 | awk 'NR==3{print $11}';vmstat 1 1 | awk 'NR==3{print $12}';vmstat 1 1 | awk 'NR==3{print $15}'

Where LANG=C lscpu | awk -F: '/Model name/ {print $2}'; , because Oracle Linux will have two nodes,  the Model Name and BIOS Model Name, so there are two lines of records when getting info

![image](https://user-images.githubusercontent.com/15188754/200469192-1fe53600-2265-409f-a835-32db7f705fc8.png)

I changed it to

LANG=C lscpu | awk -F: '$1==\"Model name\" {print $2}';awk '/processor/{core++} END{print core}' /proc/cpuinfo;uptime | sed 's/,/ /g' | awk '{for(i=NF-2;i<=NF;i++)print $i }' | xargs;vmstat 1 1 | awk 'NR==3{print $11}';vmstat 1 1 | awk 'NR==3{print $12}';vmstat 1 1 | awk 'NR==3{print $15}'

The script that gets info  LANG=C lscpu | awk -F: '$1==\"Model name\" {print $2}';

### Expected Behavior

![image](https://user-images.githubusercontent.com/15188754/200469490-0de54fe6-99e1-426a-8f12-d77b1cc98069.png)

### Environment

```markdown
HertzBeat version(s):  latest version
```

**Comment by assassinfym** [comment]
Oracle Linux关于lscpu 返回信息
![image](https://user-images.githubusercontent.com/15188754/200469912-8c41f6dd-3e2d-4466-940c-25005fa6d527.png)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Oracle Linux returns information about lscpu
![image](https://user-images.githubusercontent.com/15188754/200469912-8c41f6dd-3e2d-4466-940c-25005fa6d527.png)

**Comment by tomsun28** [comment]
Hi thanks for this issue.👍👍👍  Can you contribute a pr to fix it 😊.

**Comment by tomsun28** [comment]
hi thanks for pr! this has supported in verison v1.2.2 now! #467
