### ISSUE TITLE
[Task] <Unit Test Case>  com/usthe/alert/controller/AlertDefinesController.java

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#441]
### Description

Help us impl Unit Test For [com/usthe/alert/controller/AlertDefinesController.java](https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/controller/AlertDefinesControllerTest.java)     
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ]  Impl Unit Test For [com/usthe/alert/controller/AlertDefinesController.java](https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/controller/AlertDefinesControllerTest.java)

**Comment by aiai97** [comment]
please assign this task to me

**Comment by SurryChen** [comment]
please assign this task to me if others don't have time
