### ISSUE TITLE
[Task] <Unit Test Case> com/usthe/alert/AlerterWorkerPool.java

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#443]
### Description

Help us impl Unit Test For [com/usthe/alert/AlerterWorkerPool.java](https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/AlerterWorkerPoolTest.java)
     
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ]  Impl Unit Test For [com/usthe/alert/AlerterWorkerPool.java](https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/AlerterWorkerPoolTest.java)

**Comment by 898349230** [comment]
how to test threadpool， has some example

**Comment by tomsun28** [comment]
@898349230  welcome, Hi we use Mockito to mock instance/data to test. The example https://github.com/dromara/hertzbeat/blob/master/collector/src/test/java/com/usthe/collector/util/CollectUtilTest.java you can refer.
