### ISSUE TITLE
[Task] <Unit Test Case> com/usthe/alert/util/AlertTemplateUtil.java

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#444]
### Description

Help us impl Unit Test For [com/usthe/alert/util/AlertTemplateUtil.java](https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/util/AlertTemplateUtilTest.java) 
     
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ]  Impl Unit Test For [com/usthe/alert/util/AlertTemplateUtil.java](https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/util/AlertTemplateUtilTest.java)

**Comment by Daydreamer-ia** [comment]
can i try？
