### ISSUE TITLE
Hope to increase the LInux process monitoring function

### ISSUE THREAD

**Issue by CharlieXCL** [dromara/hertzbeat#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

希望可以增加LInux进程监控功能，大多数情况下更想关注部署在服务器上的具体服务的内存和CPU占用情况。

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
got it

**Comment by tomsun28** [comment]
support in version v1.2.2 now! #467
