### ISSUE TITLE
[Task] how to batch export or import monitoring settings, batch tag or group settings

### ISSUE THREAD

**Issue by macaty** [dromara/hertzbeat#468]
### Description

This is a very good project. We want to test it in some scenarios and hope it can support

1. Support batch export or import monitoring settings

2. Support batch tag or group settings

### Task List

-[1]  batch export or import monitoring settings
-[2]  batch tag or group settings

**Comment by tomsun28** [comment]
hi, weclome to use. These features not support now, but ```batch export or import monitoring``` would be added in roadmap!

**Comment by tomsun28** [comment]
hi, this feature has supported.
