### ISSUE TITLE
[feature]支持ElasticSearch监控类型

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#48]
**Is your feature request related to a problem? Please describe.**
支持ElasticSearch监控类型 
使用单链接直连ES，获取其性能数据指标，基本信息指标

**Comment by wang1027-wqh** [comment]
complete

**Comment by shiny** [comment]
@wang1027-wqh 请问下 es 的用户需要什么样的权限

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@wang1027-wqh What kind of permissions do es users need?
