### ISSUE TITLE
[Task] docker compose deploy script to deploy hertzbeat + mysql + iotdb

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#531]
### Description

- [ ]   provider the docker compose deploy script to deploy `hertzbeat + mysql + iotdb` 
- [ ]  refer to existing `hertzbeat + mysql + tdengine` compose script  https://github.com/dromara/hertzbeat/tree/master/script/docker-compose 
- [ ]  provider docs

**Comment by fengshunli** [comment]
support https://github.com/dromara/hertzbeat/pull/539

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
support https://github.com/dromara/hertzbeat/pull/539
