### ISSUE TITLE
[Task] <Dependency component license has 1 high risk - AGPL-3.0 - com.taosdata.jdbc:taos-jdbcdriver>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#552]
### Description

Dependency component license has 1 high risk - AGPL-3.0 - com.taosdata.jdbc:taos-jdbcdriver.    
We can not use AGPL-3.0 project in apache2 license project. 

### Task List

- [ ] Task Upgrade  com.taosdata.jdbc:taos-jdbcdriver-2.0.36[AGPL-3.0] to com.taosdata.jdbc:taos-jdbcdriver-2.0.42[MIT]. 
- [ ] Task Test Working. 

```
<!-- https://mvnrepository.com/artifact/com.taosdata.jdbc/taos-jdbcdriver -->
<dependency>
    <groupId>com.taosdata.jdbc</groupId>
    <artifactId>taos-jdbcdriver</artifactId>
    <version>2.0.42</version>
</dependency>
```

**Comment by NavinKumarBarnwal** [comment]
Hi @tomsun28 ,

I did the required change and created PR. Can you please review?

**Comment by tomsun28** [comment]
@tomsun28 OK 👍👍
