### ISSUE TITLE
[Question] <<The port configuration problem of zookeeper>

### ISSUE THREAD

**Issue by z641205699** [dromara/hertzbeat#556]
### Question

文档中心-帮助文档-中间件-zookeeper监控-配置参数
原文：端口 | Zookeeper对外提供的端口，默认为2181。
-- | --
实际配置：

端口 | Zookeeper部署的linux服务器的端口。
-- | --

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

Documentation Center-Help Documentation-Middleware-zookeeper Monitoring-Configuration Parameters
Original: Port | The port provided by Zookeeper, the default is 2181.
-- | --
Actual configuration:

Port | The port of the linux server deployed by Zookeeper.
-- | --

**Comment by tomsun28** [comment]
👍👍 能帮忙修改下这个问题提交一波PR吗

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
👍👍 Can you help to modify this problem and submit a wave of PR
