### ISSUE TITLE
[Question] I hope the front end of the monitoring report can have a timing refresh function

### ISSUE THREAD

**Issue by lancer2** [dromara/hertzbeat#581]
### Question

目前只能手动刷新页面来查看最新的监控数据,而且页面的看板较多的情况下只能手动刷新也太麻烦了
希望能像grafana的看板一样支持页面数据的定时刷新

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

At present, the page can only be manually refreshed to view the latest monitoring data, and it is too troublesome to manually refresh the page when there are many kanbans
I hope to support the timing refresh of page data like grafana's kanban

**Comment by tomsun28** [comment]
hi this has supported by pr #604

**Comment by tomsun28** [comment]
support in v1.3.0
