### ISSUE TITLE
[BUG] Front-end display，Alarm notification keeps spinning in circles occasionally

### ISSUE THREAD

**Issue by Howe9527** [dromara/hertzbeat#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Click the notification button, the pop-up window keeps spinning for more than a minute, this happens occasionally. But the request response is done in milliseconds. And another request is sent after I close the popup.

![image](https://user-images.githubusercontent.com/64837980/213348861-464b4bf3-04fb-409f-87eb-c348a7545776.png)

### Expected Behavior

Immediately display the content after clicking, do not keep spinning.

### Steps To Reproduce

Repeatedly click the notification button.

### Environment

```markdown
HertzBeat version(1.1.1):
```

**Comment by tomsun28** [comment]
thanks. we will fix it.

**Comment by tomsun28** [comment]
fix by https://github.com/dromara/hertzbeat/pull/605
