### ISSUE TITLE
Alert Notify

### ISSUE THREAD

**Issue by muslimcodeid** [dromara/hertzbeat#606]
### Question

Hi Guys,

I just installed hertzbeat on my server using docker,refer to this link : https://techviewleo.com/monitor-linux-systems-using-hertzbeat/

I can access the WEB UI,however there is some question i need to ask

1. I can add my alert notify to telegram because there is option to telegram,you can refer to the screenshot below :
   https://postimg.cc/ts949bY2
   
2. If i want to monitor another server and how to install an agent to the server target ?

Please Advice

Thanks in advance

**Comment by tomsun28** [comment]
Hi, thanks for using.  The `telegram notify` has supported but not publish in latest version. It will supported in next version v1.2.5 few days later.  
> 2. If i want to monitor another server and how to install an agent to the server target ?   

hertzbeat is agentless. you can monitor linux ubuntu... directly by configing `ip port ssh params` with WEB UI.

**Comment by muslimcodeid** [comment]
Hi @tomsun28,

Thanks for your time to reply.

Noted On this.
