### ISSUE TITLE
[BUG] 监控历史数据趋势图，监控指标显示为NULL

### ISSUE THREAD

**Issue by cnskylee** [dromara/hertzbeat#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

监控历史数据趋势图，监控指标显示为NULL，并且数据的单位（比如：Bytes）也没写，建议修复和完善
![0d11ff9f766f8e896c4f900eb80e021](https://user-images.githubusercontent.com/23625153/216494744-74949986-2dfc-4f70-aad7-a990fb4c6fe2.png)

### Expected Behavior

监控历史数据趋势图，监控指标显示为NULL，并且数据的单位（比如：Bytes）也没写，建议修复和完善

### Steps To Reproduce

无

### Environment

```markdown
HertzBeat version(s):1.2.4
```

### Debug logs

无

### Anything else?

无

**Comment by tomsun28** [comment]
done by https://github.com/dromara/hertzbeat/pull/615
