### ISSUE TITLE
[Question] Alert Settings

### ISSUE THREAD

**Issue by muslimcodeid** [dromara/hertzbeat#620]
### Question

Hi Guys,

Thanks for your latest update for docker image.

I just setup this hertzbeat on our server  using docker(docker run -d -p 1157:1157 --name hertzbeat tancloud/hertzbeat),
we have added Ubuntu Linux(OS Monitor) the metrics should be fine,because i can see from the dashboard that this monitoring system could collect all the metrics from the target server.

I setup the alert notify to telegram and its successfully send the test alert and i also setup the alert setting,you can refer to the screenshot below :
![image](https://user-images.githubusercontent.com/63686253/217169377-9bef08e1-b31a-468c-9ab7-80e6aec2cbd9.png)

fyi, current usage for "/" (root) is 65 % already but its not send any alert.

Please Advice

Thanks in advance

**Comment by tomsun28** [comment]
Hi, if you have added Ubuntu Linux(OS Monitor) by **Ubuntu Linux**, the alert setting metric target should be `Ubuntu Linux` not `Linux`. 

<img width="904" alt="2023-02-07 15 34 03" src="https://user-images.githubusercontent.com/24788200/217180280-71034dc2-84a4-41ad-8d3a-7a8d8d993d32.png">

**Comment by muslimcodeid** [comment]
Hi @tomsun28,

Thanks for your reply.

I make it already,

Regarding the notification rule,is it possible to send the notification only once per policy so it wont send the same notification repeatedly

Please Advice

Thanks in advance

**Comment by tomsun28** [comment]
> Regarding the notification rule,is it possible to send the notification only once per policy so it wont send the same notification repeatedly

Hi, the notification policy are each independent, can not send only once per policy.  

If you worry about too many same alerts. We will support alarm grouping and alarm silence some time later

**Comment by muslimcodeid** [comment]
Hi,

Thanks for that

Appreciate that
