### ISSUE TITLE
[BUG] The cover of the big screen is too small BUG

### ISSUE THREAD

**Issue by zanglikun** [dromara/hertzbeat#641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/61591648/218899026-60dc05ab-51ea-4655-8b72-e0236925ac7c.png)

### Expected Behavior

正常展示 当前是mac 外界4K显示器下 导致的。前端自己懂具体原因。

### Steps To Reproduce

无需尝试，懂前端的知道问题在哪

### Environment

```markdown
HertzBeat version(s):1.25
```

### Debug logs

no logs

**Comment by tomsun28** [comment]
Got it.

**Comment by tomsun28** [comment]
fix by v1.3.0
