### ISSUE TITLE
[BUG] The memory of the monitoring server cannot be monitored in the case of Chinese

### ISSUE THREAD

**Issue by zhgkwzf** [dromara/hertzbeat#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

监控服务器在中文情况下内存无法监控

### Environment

```markdown
HertzBeat version(s):v1.2.3
```

**Comment by tomsun28** [comment]
Got it.

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Got it.

**Comment by tomsun28** [comment]
replace https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-linux.yml#L190
```
free -m | grep Mem | awk 'BEGIN{print "total used free buff_cache available"} {print $2,$3,$4,$6,$7}'
```
to 
```
free -m | awk 'BEGIN{print "total used free buff_cache available"} NR==2{print $2,$3,$4,$6,$7}'
```

**Comment by ByteIDance** [comment]
领取任务

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
recieve the task
