### ISSUE TITLE
Always push UN_CONNECTABLE errors for indicators that have not been monitored

### ISSUE THREAD

**Issue by QZmp236478** [dromara/hertzbeat#653]
### Question

设置监控项为取消监控后会一直推送UN_CONNECTABLE错误，推送频率为30分钟左右一次。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

After setting the monitoring item to cancel the monitoring, the UN_CONNECTABLE error will be pushed all the time, and the push frequency is about once every 30 minutes.
