### ISSUE TITLE
[Task] The versions of the dependencies should be define in the main pom.xml file

### ISSUE THREAD

**Issue by HattoriHenzo** [dromara/hertzbeat#667]
### Description

The versions of the dependencies should be defines into the main `pom.xml` file precisely in the `dependencyManagement` section. 
We can make some changes in the projects main `pom.xml` files and child modules.
Also, all dependencies versions should be define in the `properties` section.

**Comment by tomsun28** [comment]
common used dependencies should been put main pom.xml `dependencyManagement`, child module special dependency do not need

**Comment by HattoriHenzo** [comment]
@tomsun28 you can assign it to me.

**Comment by tomsun28** [comment]
done！👍
