### ISSUE TITLE
[Question] High Load Issue

### ISSUE THREAD

**Issue by muslimcodeid** [dromara/hertzbeat#695]
### Question

Hi,

I am experiencing an issue and this issue is frequently happened.
I get High load on my CPU and Memory and to fix this issue i need to restart my container ( i run hertzbeat as docker) and always the service which has high load is java -server -XX:SurvivorRatio=6 -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/hertzbeat/logs -Dlogging.path+

I also found that i get this logs from my logs file,you can refer to the link below :

https://pastebin.com/emMCxJn6

Please Advice

Thanks in advance

**Comment by tomsun28** [comment]
thanks for feedback.

**Comment by tomsun28** [comment]
what is the hertzbeat version, can you give us the OOM HeapDump file `xxx.hprof` to analyze

**Comment by muslimcodeid** [comment]
Hi,

Thanks for your reply

We are using HertzBeat v1.2.5 with latest image docker

As per i check the file is quite big if you need to check it i will try to upload the file from the cloud like google drive

-rw------- 1 root root 1.1G Mar  4 00:53 java_pid10.hprof
-rw------- 1 root root 902M Feb 25 19:56 java_pid9.hprof

Best Regards,

**Comment by muslimcodeid** [comment]
Hi @tomsun28,

You can download the .hprof from the link below :

[Download](https://bit.ly/3L4As37)

Thanks in advance

**Comment by tomsun28** [comment]
hi please upload `java_pid9.hprof`. we need it thanks.

**Comment by tomsun28** [comment]
> Hi @tomsun28,
> 
> You can download the .hprof from the link below :
> 
> [Download](https://bit.ly/3L4As37)
> 
> Thanks in advance

thanks

**Comment by muslimcodeid** [comment]
> > Hi @tomsun28,
> > You can download the .hprof from the link below :
> > [Download](https://bit.ly/3L4As37)
> > Thanks in advance
> 
> thanks

You're welcome

**Comment by tomsun28** [comment]
@muslimcodeid hi, thanks for feedback and your hprof file. This is an oom bug due users not config tdengine database or iotdb database to store metrics data. We have fix it in latest docker image now. You can pull latest docker images from https://hub.docker.com/r/tancloud/hertzbeat/tags  

Thanks 👍

**Comment by muslimcodeid** [comment]
Hi @tomsun28,

I have pulled the latest image

Thanks for your help
