### ISSUE TITLE
[Task] <change default monitor intervals 120s to 60s>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#703]
### Description

change default monitor intervals 120s to 60s when add or edit monitor in web ui

just update https://github.com/dromara/hertzbeat/blob/master/web-app/src/app/pojo/Monitor.ts#L8

**Comment by aywmm0325** [comment]
领取任务

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
recieve the task

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
recieve the task

**Comment by Grass-Life** [comment]
领取任务

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
recieve the task

**Comment by ByteIDance** [comment]
领取任务

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
recieve the task
