### ISSUE TITLE
[Task] <change alert define trigger times from max 10 to max 999>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#704]
### Description

change alert define trigger times from max 10 to max 999.  

update this `nzMax ` https://github.com/dromara/hertzbeat/blob/master/web-app/src/app/routes/alert/alert-setting/alert-setting.component.html#LL215

**Comment by ByteIDance** [comment]
领取任务

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
recieve the task

**Comment by xiaohe428** [comment]
领取任务

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
recieve the task

**Comment by Grass-Life** [comment]
领取任务

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
recieve the task
