### ISSUE TITLE
告警邮件内的“登入控制台”链接无法配置

### ISSUE THREAD

**Issue by 303snowing** [dromara/hertzbeat#71]
![image](https://user-images.githubusercontent.com/26240884/161874823-7d78b9f8-30fe-4ca6-a380-0ecf1b43f0c1.png)

**Comment by tomsun28** [comment]
hi 这个目前是写固定的还不支持配置，可以先改代码把这个链接修改成自己的部署网站   
代码位于项目的 manager/src/main/resources/templates/mailAlarm.html

**Comment by tomsun28** [comment]
后面我们把这个支持下
