### ISSUE TITLE
【希望可以支持SNMP协议监控】并且能自定义监控项，对接硬件接口和网络设备

### ISSUE THREAD

**Issue by acdante-zhang** [dromara/hertzbeat#73]
【希望可以支持SNMP协议监控】并且能自定义监控项，对接硬件接口和网络设备

**Comment by tomsun28** [comment]
谢谢建议，收到，已加入roadmap 后续支持

**Comment by tomsun28** [comment]
hi snmp support!   https://github.com/dromara/hertzbeat/releases/tag/v1.1.0  welcome to use
