### ISSUE TITLE
[Task] <title>We hope to add WeChat application messages for message push

### ISSUE THREAD

**Issue by gaows20** [dromara/hertzbeat#736]
### Description

消息推送希望可以新增微信应用消息（微信就可以接收消息了，可以不用在下载企业微信app了）
开放API：

https://developer.work.weixin.qq.com/document/path/90236#%E6%8E%A5%E5%8F%A3%E5%AE%9A%E4%B9%89

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

Message push hopes to add WeChat application messages (WeChat can receive messages, and you don’t need to download the enterprise WeChat app)
Open APIs:

https://developer.work.weixin.qq.com/document/path/90236#%E6%8E%A5%E5%8F%A3%E5%AE%9A%E4%B9%89

### Task List

_No response_

**Comment by hudongdong129** [comment]
please assign this task to me

**Comment by tomsun28** [comment]
this feature has supported! 👍 thanks @hudongdong129
