### ISSUE TITLE
[Question] Do you plan to add rocketMQ and linux secret key login

### ISSUE THREAD

**Issue by wangdazhong001** [dromara/hertzbeat#738]
### Question

1、The current version of server monitoring linux does not support secret key login
2、Are there plans to add rocketMQ to middleware?

**Comment by kunalznk** [comment]
can i work on this

**Comment by tomsun28** [comment]
> can i work on this

@kunalznk 👍 of course, welcome

**Comment by tomsun28** [comment]
the rocketMQ and linux secret key login features have supported.

**Comment by wangdazhong001** [comment]
very good
