### ISSUE TITLE
Table does not exist

### ISSUE THREAD

**Issue by zhangyenull** [dromara/hertzbeat#74]
TDengine ERROR (362): sql: SELECT ts, instance, responseTime FROM telnet_summary_7014836797177856 WHERE ts >= now - 6h order by ts desc, desc:  这是怎么回事呢

**Comment by tomsun28** [comment]
hi 谢谢反馈 这个在监控数据还没入库到tdengine时，页面点击查询历史图表就会报这个错，因为那时无监控数据还没有自动创建表，属于正常情况，后面我们把它优化掉

**Comment by tomsun28** [comment]
hi, the version [hertzbeat v1.0](https://github.com/dromara/hertzbeat/releases/tag/v1.0) has fix it
