### ISSUE TITLE
[Task] <nacos monitoring support auth>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#747]
### Description

now nacos monitoring can not config username, password to access. 

### Task List

- [ ] support config username, password or token to monitoring nacos metrics when it need authing.

**Comment by vinci-897** [comment]
Hello, I am a undergraduate from Zhejiang University in China and will enroll in my master degree in 2023.9. I noticed that there is many good first issue and enhancement of heartbeat on GitHub. I have much time recently and am very interested in this project. Can you assign some issues to me? I’m very glad to contribute.

**Comment by vinci-897** [comment]
Hello, I am a undergraduate from Zhejiang University in China and will enroll in my master degree in 2023.9. I noticed that there is many good first issues and enhancements of heartbeat here. I have much time recently and am very interested in this project. Can you assign some issues to me? I’m very glad to contribute.

**Comment by tomsun28** [comment]
hi welcome coding with us. This task has been assigned to you.

**Comment by vinci-897** [comment]
done
