### ISSUE TITLE
网站无法打开 ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by youmengme** [dromara/hertzbeat#87]
https://console.tancloud.cn/
https://tancloud.cn/
均无法打开 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/27558572/162938979-85f2dfe0-4fca-437b-9a8c-3b5803c64907.png">
<img width="879" alt="image" src="https://user-images.githubusercontent.com/27558572/162938995-50d4a0f3-4e1f-4013-bf07-db9bff80e5b1.png">

**Comment by tomsun28** [comment]
这两个网站都挂了CDN 我去排查下

**Comment by tomsun28** [comment]
hi @youmengme 感谢反馈 之前是因为CDN赞助在测试 目前已恢复
