### ISSUE TITLE
[Task] <set the special field string length when jpa auto ddl>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#870]
### Description

set the special field string length when jpa auto ddl 
eg: `tags` field length 2048

### Task List

- [ ] set the special field string length when jpa auto ddl

**Comment by dhruva1995** [comment]
Hey @tomsun28, can you please elaborate the issue in detail, I am just getting started on places where I could contribute, I am happy to complete this.

**Comment by tomsun28** [comment]
hi welcome @dhruva1995. 
Now we use jpa auto ddl to auto create table when startup first time. If we do not customize the table field type length, the default table field string length is varchar(255), which is not enough for some special fields such as `tags`, and will cause exception when the field is too long.
So this task is to config the special field string length in `@Table` file by using java code `@Column(length = 2048)`
Example Before.
```java
    @Schema(description = "Tags(monitorId:xxx,monitorName:xxx)", example = "{name: key1, value: value1}",
            accessMode = READ_WRITE)
    @Convert(converter = JsonTagListAttributeConverter.class)
    private List<TagItem> tags;
```
Update:
```java
    @Schema(description = "Tags(monitorId:xxx,monitorName:xxx)", example = "{name: key1, value: value1}",
            accessMode = READ_WRITE)
    @Convert(converter = JsonTagListAttributeConverter.class)
    @Column(length = 2048)
    private List<TagItem> tags;
```

special table fields: `tags`, `content`, `template`, `Param->value`

**Comment by dhruva1995** [comment]
Hi @tomsun28 probably you can close this task.

**Comment by tomsun28** [comment]
> Hi @tomsun28 probably you can close this task.

ok thanks. it has supported in v1.3.1
