### ISSUE TITLE
[Question] Custom Monitoring param, custom host field name do not work

### ISSUE THREAD

**Issue by jvhuaxia** [dromara/hertzbeat#890]
### Question

![image](https://user-images.githubusercontent.com/29006793/232433692-33a2dc90-99a3-4f01-8210-514558ade769.png)
i custom host field name but is not work
![image](https://user-images.githubusercontent.com/29006793/232434050-4df8efe4-9298-4ecf-9859-d091354e6306.png)

**Comment by jvhuaxia** [comment]
i want UI show ZabbixWebHost

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
i want UI show ZabbixWebHost

**Comment by tomsun28** [comment]
hi, the field `host` can not custom.
