### ISSUE TITLE
hertzbeat keyword bug when using TDengine query.

### ISSUE THREAD

**Issue by 2406450951** [dromara/hertzbeat#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用TDengine查询未处理关键字问题。
![a5d7705caa451c4d5f2f08dfb42b220](https://user-images.githubusercontent.com/48074721/233533721-17332ef3-7c66-4667-afcf-379414a56322.png)

### Expected Behavior

增加对关键字的处理。

### Environment

```markdown
HertzBeat version(s):1.3
```

### Debug logs

![a5d7705caa451c4d5f2f08dfb42b220](https://user-images.githubusercontent.com/48074721/233533753-9e002dc3-2479-44c1-a6d0-48c769b0b0a1.png)

**Comment by 2406450951** [comment]
已解决

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
solved
