### ISSUE TITLE
[BUG] <There is a problem with monitoring and collection>

### ISSUE THREAD

**Issue by 305467425** [dromara/hertzbeat#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我先配置了网站监控和http-api监控各一个，采集间隔时间60s，正常采集监控运行；
我删除网站监控后，http-api会开始不间断采集，无视采集间隔配置，同时停止采集功能会失效

### Steps To Reproduce

1、配置网站监控，采集间隔时间60s，正常采集监控运行；
2、配置http-api监控，采集间隔时间60s，正常采集监控运行；
3、删除网站监控
4、http-api会开始不间断采集，无视采集间隔配置，同时停止采集功能会失效

### Environment

```markdown
HertzBeat version(s):docker.io/tancloud/hertzbeat:latest
```

**Comment by tomsun28** [comment]
hi 此问题已修复 请刷新最新的镜像或安装包

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi This problem has been fixed, please refresh the latest image or installation package
