### ISSUE TITLE
[BUG] <label missing>

### ISSUE THREAD

**Issue by abigdream** [dromara/hertzbeat#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

如果删除一个带有自定义标签的主机，那么删除主机的同时，标签管理中的标签也会被删除。

### Expected Behavior

no

### Steps To Reproduce

no

### Environment

```markdown
no
```

### Debug logs

no

### Anything else?

no

**Comment by tomsun28** [comment]
fix by v1.3.1
