### ISSUE TITLE
希望有分组/tag功能

### ISSUE THREAD

**Issue by aloasut** [dromara/hertzbeat#92]
作为APM希望可以把不同的项目通过分组/tag汇总起来。
例如一个项目既有http监控，也有ping监控，也有tcp监控；这个项目任何一个服务出问题就可以通知某个人。
另外所有的项目最好都加上个说明字段，以便监控人员知道这个是干什么用的。

**Comment by tomsun28** [comment]
收到 谢谢很有用的建议

**Comment by tomsun28** [comment]
support #111  next version v1.0.beat.8
