### ISSUE TITLE
[BUG] update the description of https://github.com/dromara/hertzbeat/releases/tag/v1.3.1

### ISSUE THREAD

**Issue by liudonghua123** [dromara/hertzbeat#928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current `Upgrade Note⚠️.` of https://github.com/dromara/hertzbeat/releases/tag/v1.3.1 has some issues.
1. `ALTER table HZB_ALERT_DEFINE modify FIELD varchar(255) default null;` should be `ALTER table hzb_alert_define modify field varchar(255) default null;`
2. The Chinese `升级注意⚠️.` part is not corresponding to the English version.

### Environment

```markdown
HertzBeat version(s): 1.3.1
```

### Anything else?

I have updated the release notes. (It's strange I can modify it directly. Maybe I have some permission to do so. :hah)

**Comment by tomsun28** [comment]
thanks👍
