### ISSUE TITLE
[Question] <Question about zookeeper monitoring>

### ISSUE THREAD

**Issue by sppan24** [dromara/hertzbeat#947]
### Question

存在的疑问：
1. `zk`的监控是基于`nc`命令来实现的，那为什么还会需要基于`ssh`协议？
2. 现在的内置`zk`监控模板`app-zookeeper.yml`，在基于`ssh`协议的基础上，执行的诸如`echo mntr | nc 121.40.113.44 2181`命令，是不正确的，如果需要监控多台`zk`，每个都需要改对应的`ip地址`，也就是说需要重新自定义监控来实现。为何不直接通过变量的形式控制即可？

我的个人考虑，是否应该直接支持`nc`协议，不需要`over ssh`会更合理一些？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

Existing doubts:
1. The monitoring of `zk` is implemented based on the `nc` command, so why is it still based on the `ssh` protocol?
2. The current built-in `zk` monitoring template `app-zookeeper.yml`, based on the `ssh` protocol, executes commands such as `echo mntr | nc 121.40.113.44 2181`, which is incorrect. If necessary To monitor multiple `zk`, each needs to change the corresponding `ip address`, that is to say, it needs to re-customize the monitoring to achieve. Why not directly control it in the form of variables?

In my personal consideration, should the `nc` protocol be directly supported, and it would be more reasonable not to require `over ssh`?

**Comment by tomsun28** [comment]
hi 谢谢反馈 看你的分析我觉得是的👍 欢迎贡献一波直接基于 `nc` 来监控zookeeper 或者看 zookeeper 有没有其他类似对外接口我们可以采集数据监控

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, thank you for your feedback. I think it is based on your analysis 👍 Welcome to contribute a wave of monitoring zookeeper directly based on `nc` or see if zookeeper has other similar external interfaces that we can collect data monitoring

**Comment by sppan24** [comment]
经过我的分析实验，`zookeeper`的监控完全可以基于`telnet`来实现和`nc`命令相同的效果。为了不增加系统复杂性，我扩展了项目里面的`telnet`协议，可以支持在`telnet`到指定端口后发送命令并解析响应结果。在这个基础上，可以实现`zookeeper`的监控，同时不需要`ssh`到对应的服务器上。具体实现我已经提交了`PR`，见 #957

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
After my analysis and experiments, the monitoring of `zookeeper` can be based on `telnet` to achieve the same effect as the `nc` command. In order not to increase the complexity of the system, I extended the `telnet` protocol in the project, which can support sending commands and parsing the response results after `telnet` reaches the specified port. On this basis, `zookeeper` monitoring can be realized without `ssh` to the corresponding server. I have submitted `PR` for specific implementation, see #957

**Comment by tomsun28** [comment]
> 经过我的分析实验，`zookeeper`的监控完全可以基于`telnet`来实现和`nc`命令相同的效果。为了不增加系统复杂性，我扩展了项目里面的`telnet`协议，可以支持在`telnet`到指定端口后发送命令并解析响应结果。在这个基础上，可以实现`zookeeper`的监控，同时不需要`ssh`到对应的服务器上。具体实现我已经提交了`PR`，见 #957

太强了 👍

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> After my analysis and experiments, the monitoring of `zookeeper` can be based on `telnet` to achieve the same effect as the `nc` command. In order not to increase the complexity of the system, I extended the `telnet` protocol in the project, which can support sending commands and parsing the response results after `telnet` reaches the specified port. On this basis, `zookeeper` monitoring can be realized without `ssh` to the corresponding server. I have submitted `PR` for specific implementation, see #957

too strong 👍
