### ISSUE TITLE
监控历史图表详情，时区错误

### ISSUE THREAD

**Issue by gcdd1993** [dromara/hertzbeat#96]
**Describe the bug**
监控历史图表详情时间显示错误，显示的是UTC时间，实际是东八区
![image](https://user-images.githubusercontent.com/26523525/163678140-d84b66c7-3518-4a3b-80d4-2601caaa24f2.png)
![image](https://user-images.githubusercontent.com/26523525/163678172-70077667-bf8d-4b3c-9b22-a0a500b8d479.png)

**Used Version**  
 1.0 beta7

**Comment by tomsun28** [comment]
此为tdengine时序数据库未设置时区导致，请参考下面在部署tdengine时设置对应的时区
<img width="1087" alt="截屏2022-04-17 08 13 31" src="https://user-images.githubusercontent.com/24788200/163695122-c4aa29f3-8cde-4119-b26a-2455aaa7daea.png">
