### ISSUE TITLE
[Question] <Monitoring address domain name verification logic question>

### ISSUE THREAD

**Issue by sppan24** [dromara/hertzbeat#962]
### Question

理论上说，监控系统主要运行在内网环境，在一些企业内部，会存在内部域名。在不是很严谨的情况下，可能将一些常见字符（例如下划线）作为内部域名。这样会导致没法接入监控。我个人认为，可以考虑放开部分常见字符限制。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

Theoretically speaking, the monitoring system mainly operates in the intranet environment, and in some enterprises, there will be internal domain names. In less rigorous cases, some common characters (such as underscore) may be used as internal domain names. This will result in inability to access monitoring. Personally, I think you can consider relaxing some common character restrictions.

**Comment by tomsun28** [comment]
确实是这样 可以的👍👍 有兴趣改一波吗😄

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This is indeed the case 👍👍 Are you interested in changing it? 😄

**Comment by sppan24** [comment]
> 确实是这样 可以的👍👍 有兴趣改一波吗😄

目前通过我们公司的场景来看，出现比较多的就是下划线，我已经做了兼容，详情见 #963

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> This is indeed the case 👍👍 Are you interested in changing it 😄

At present, according to the scene of our company, underscores appear more frequently. I have made compatibility, see #963 for details

**Comment by tomsun28** [comment]
👍
