### ISSUE TITLE
[BUG] Footer Overflow on HomePage

### ISSUE THREAD

**Issue by eeshaanSA** [dromara/hertzbeat#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

##Issue
Currently the footer is badly messed up and is not resposive. Check https://hertzbeat.com/
![image](https://github.com/dromara/hertzbeat/assets/100678386/d20b742a-35dc-4cdb-8469-084bbf6f9ef3)

### Expected Behavior

##Suggested Changes / Mockups
The footer to be made responsive and overflow should be prevented, with some color changes to distinguish it from the rest of the body.  
-Mockup 

[Screencast from 20-05-23 05:58:46 PM IST.webm](https://github.com/dromara/hertzbeat/assets/100678386/75d90bbb-f76a-4764-b60f-b255ba3f0516)

### Steps To Reproduce

inspect the navbar for respnsiveness and go below 900px 

### Environment

```markdown
HertzBeat version(s):
```

**Comment by eeshaanSA** [comment]
@tomsun28 please confirm whether I can start working on this, more than pleased to do so.

**Comment by eeshaanSA** [comment]
Check Pull #973

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Check Pull #973

**Comment by tomsun28** [comment]
> @tomsun28 please confirm whether I can start working on this, more than pleased to do so.

ok 👍👍
