### ISSUE TITLE
[BUG] <title> After exporting monitoring, modify the bug when importing

### ISSUE THREAD

**Issue by love19791126** [dromara/hertzbeat#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在配置一个端口监控-导出监控，修改里面的IP后（因为我这都是负载2台机器除了IP其他都一样），在导入发现原始标签ID和新便签ID出现了2次，其次建议增加主机host多次填写按钮，这样2个机器增加一个服务，然后便签随机生成2次。
monitorld:255031608004864 （建议此处导出不含id 导入的随机新增）
monitorName:PORT_172.17.0.49-后端-station-prciemonitorld:255031862857984
monitorld:255031608004864 （建议此处导出不含id 导入的随机新增）
monitorName:PORT_172.17.0.30-后端-station-prcie

### Debug logs

在配置一个端口监控-导出监控，修改里面的IP后（因为我这都是负载2台机器除了IP其他都一样），在导入发现原始标签ID和新便签ID出现了2次，其次建议增加主机host多次填写按钮，这样2个机器增加一个服务，然后便签随机生成2次。
monitorld:255031608004864 (建议此处导出不含id 导入的随机新增)
monitorName:PORT_172.17.0.49-后端-station-prciemonitorld:255031862857984
monitorld:255031608004864（建议此处导出不含id 导入的随机新增）
monitorName:PORT_172.17.0.30-后端-station-prcie

**Comment by love19791126** [comment]
![image](https://github.com/dromara/hertzbeat/assets/33218166/57a9a91f-faef-4b9b-bf0a-1f8645821820)

**Comment by l646505418** [comment]
Hi， @love19791126 ，你能提供一下重现这个问题的步骤吗？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, @love19791126, can you provide the steps to reproduce this issue?

**Comment by l646505418** [comment]
@tomsun28 好像是因为在import的时候会根据tag id，把现存的tag赋给新的monitor，在添加新的monitor的时候，又会添加id和name，所以会有两组标签。可以在import的时候过滤掉monitorId和monitorName这两个标签
