### ISSUE TITLE
[Task] <Add sshd server in hertzbeat docker image build>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#982]
### Description

Add sshd server when build hertzbeat docker image. 
We need sshd service to connect other server without password when use hertzbeat docker container. 

Dockerfile is here. https://github.com/dromara/hertzbeat/blob/master/script/docker/server/Dockerfile

### Task List

- [ ] Add sshd server when build hertzbeat docker image.

**Comment by nandofromthebando** [comment]
I am on it currently doing it now!
