### ISSUE TITLE
[Task] <support monitoring apache spark metrics>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#990]
### Description

support monitoring apache spark metrics  
we can consider use jmx protocol(or others) to monitoring spark metrics.

https://spark.apache.org/docs/latest/monitoring.html

### Task List

- [ ] support monitoring apache spark metrics
- [ ] add help doc

**Comment by a-little-fool** [comment]
I want to help

**Comment by tomsun28** [comment]
@a-little-fool welcome 👍
