### ISSUE TITLE
[Task] <support monitoring apache airflow health, metrics>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#993]
### Description

support monitoring apache airflow health, metrics
consider using http rest api protocol to collect metrics 

https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#tag/Monitoring

### Task List

- [ ] support monitoring apache airflow health, metrics
- [ ] add help doc

**Comment by luoxuanzao** [comment]
I want to help

**Comment by tomsun28** [comment]
@luoxuanzao welcome, this task has assigned to you. 👍👍

**Comment by luoxuanzao** [comment]
我们是否需要展示latest___heartbeat字段
<img width="1696" alt="image" src="https://github.com/dromara/hertzbeat/assets/44692579/97870511-1fcd-41ee-bfe8-07fa28bd0bbc">

**Comment by luoxuanzao** [comment]
Do we need to display the latest__xxx__heartbeat field?
<img width="1696" alt="image" src="https://github.com/dromara/hertzbeat/assets/44692579/d8389008-da22-4e1d-b769-c32fb53d907d">

**Comment by tomsun28** [comment]
hi 👍 I think `status` is required, `latest__xxx__heartbeat` metric can be left out if it is not good to display
